### ISSUE TITLE
Run Serval E2E tests with commits to master in Machine

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#100]
How can we do this?  We should!

**Comment by ddaspit** [comment]
We should only do this if the E2E tests are rock solid. Otherwise, we could do this on release.

**Comment by johnml1135** [comment]
They should be solid - and if they are not, we should be able to make them so.

**Comment by johnml1135** [comment]
How about this:
* It can be manually run
* It is always run when a serval or machine docker image is about to be made

**Comment by ddaspit** [comment]
By "rock solid", I mean that it doesn't fail occasionally with false positives. @johnml1135 I agree. Running it only when we "release" makes sense.

**Comment by Enkidu93** [comment]
Still waiting on updates to secrets as far as I know. Let me know if someone's done this already. @ddaspit @johnml1135

**Comment by johnml1135** [comment]
Secrets are updated

**Comment by Enkidu93** [comment]
Any updates @johnml1135 ? I'm happy to add them myself if you give me (even temporary) permissions.

**Comment by johnml1135** [comment]
@Enkidu93 - I gave you admin access to Machine.
