### ISSUE TITLE
Log client ID (and engine ID if appropriate) when returning 400 or 500 codes

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#103]
So we can better trace back to what was happening - even if it is manually.

**Comment by Enkidu93** [comment]
@johnml1135 @ddaspit 

Would something like this be appropriate:
```
serval_cntr          |       User <client_id>@clients made request:
serval_cntr          |        {
serval_cntr          |         "action": "Get",
serval_cntr          |         "controller": "TranslationEngines",
serval_cntr          |         "id": "111111111111111111111111",
serval_cntr          |         "version": "1"
serval_cntr          |       }.
serval_cntr          |        Responded with code 404. Trace: <trace_id>
```
I have this working locally.

Is it safe to log the client_id?

**Comment by ddaspit** [comment]
It should be okay to log the client ID.

**Comment by Enkidu93** [comment]
> It should be okay to log the client ID.

Sweet. I figured it was since without the secret, it's sort of like knowing someone's safety deposit box # without having his key. Just verifying.

**Comment by Enkidu93** [comment]
Added here: https://github.com/sillsdev/serval/pull/130
