### ISSUE TITLE
Build status 404 right after build is finished (for a few seconds)

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#114]
"I have noticed a brief period where Serval returns 404s just after the build has finished uploading, but then it resolves itself for me."

**Comment by Enkidu93** [comment]
Who is this quote from? What is meant by "uploading"? Does this mean a few minutes after it says it's complete, it returns 404s?

**Comment by johnml1135** [comment]
I believe it was from @Nateowami  - can you check with him on the specifics?  I don't know if I got all the details (after uploading files?  After attaching a corpus?  After starting a build?  Which command was returning 404's?

**Comment by Nateowami** [comment]
After uploading the corpus and telling the build to start.

**Comment by Nateowami** [comment]
@pmachapman may be able to provide exact details.

**Comment by johnml1135** [comment]
SF uploads 520 files (2 chapters of the Bible) and then tries to build within a few milliseconds.  I don't know if the file write operations take a few seconds to complete after responding positively.

**Comment by ddaspit** [comment]
The only way that Serval would return a 404 on the start build endpoint is if the engine does not exist. I'm guessing that it isn't the start build endpoint that is returning a 404.

**Comment by pmachapman** [comment]
@johnml1135 @Nateowami @Enkidu93 I think this occurred from a combination of SF not handling state correctly while uploading to Serval, and the issue with the S3 keys. I am not having it occur while retesting at my end.

I think we can close this, and if I have it happen again (and have a consistent procedure for recreating it) I can reopen the ticket.

**Comment by Enkidu93** [comment]
Sounds good!
