### ISSUE TITLE
Add Cancelling state for jobs

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#121]
When a job is cancelled, it moves first to "Cancelling" before Machine fully cancels the job.  A few notes:
* Cancelling Job state should be added after Canceled to preserve numbering
* If a job start is requested when a job is Cancelling, wait for a few seconds (timeout seconds - 1?) before responding while all the while checking if the cancellation completed (polling every second or subscribe).
  * Or, say "A job is Cancelling - please try again in a few seconds." - ok we can do this one

**Comment by johnml1135** [comment]
It may also require adding a engine.proto message to check status:
* Add some cleanup logic for hanging jobs
* This may be best implemented in machine or Serval

**Comment by Enkidu93** [comment]
Thoughts here @ddaspit ? My impression was you were architecting and I was implementing. I'm happy to take it on fully if you like, but wouldn't want to step on feet. (Just trying to finish up the MVP tasks).

**Comment by johnml1135** [comment]
We can do this once https://github.com/sillsdev/machine/pull/101 is merged.

**Comment by johnml1135** [comment]
This is to add the cancelling state in Serval once the cancelling state in Machine is added in https://github.com/sillsdev/machine/pull/101.

**Comment by Enkidu93** [comment]
I've reviewed the cancellation code in Serval and Machine, and I'm not sure what's left to be done here.

**Comment by johnml1135** [comment]
So if I am correct, Serval will say that it is deleted (or cancelled) right away, while Machine will have the "cancelling" state until the work is actually done?  Can we possibly add one missing E2E test (or similar) that tries to build an engine 1ms after it was running and deleted (or similar).  If the test already exists (or can be done at a unit or integration test level) then great - we can close the issue.

**Comment by Enkidu93** [comment]
I believe that the steps are:

* Serval sends a `CancelBuildRequest` to Machine
* Machine first internally cancels the build (which involves setting the `BuildJobState` to `None` if it's `Pending` and `Canceling` if it's active). Then, if it were set to `None` (i.e., was previously `Pending`), Machine un-sets the current build and sends a `BuildCanceledRequest` back to Serval at which point Serval goes ahead and sets the state to `Canceled` etc.
* Meanwhile, when/if the `ClearMLMonitorService` catches wind that the state has become `Canceling`, it sends a `BuildCanceledRequest` back to Serval at which point Serval goes ahead and sets the state to `Canceled` etc. Then it 'finishes' the job: un-setting the current build and incrementing the `BuildRevision`.

 So the odd behavior is that if you request a build while it's `Canceling` in Machine, it will still say it's `Active` briefly (~10 seconds at the moment, I believe). You could add the `Canceling` state to Serval and another request in platform.proto that marks the build as `Canceling`, but I'm not sure that this is necessary. As for starting a build while the previous build is still canceling, currently, it will throw an exception saying "The engine has already started a build". Maybe the best solution on this side is to update the message to be something like "The engine is already building or in the process of canceling.", and then add a test in `NmtEngineServiceTests`. Thoughts, @johnml1135?

**Comment by johnml1135** [comment]
The swagger documentation update is probably enough - we don't even need the test.

**Comment by Enkidu93** [comment]
Do you mean the update to the exception message? Alright, I'll go ahead and take care of that.
