### ISSUE TITLE
Paratext zipped file - E2E "missing" test 

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#125]
Add one.

**Comment by johnml1135** [comment]
Also, make at least one of the para text projects over 5MB so that the partial upload/download can be tested.

**Comment by johnml1135** [comment]
And add more description of what a "paratext" project is in openapi.  Give a very simple directory structure, noting that it is not a zipped folder, but a zipped collection of files.

**Comment by Enkidu93** [comment]
Is there a way I can get/use Paratext and generate sample data? I've never touched it before. This would also be helpful for [this](https://github.com/sillsdev/machine/issues/77). And maybe just in general.

**Comment by johnml1135** [comment]
Yes - you should be able to register here and say you are a developer - https://paratext.org/registration/

**Comment by Enkidu93** [comment]
Fixed in merge above.
