### ISSUE TITLE
Add test - delete an engine with a running build

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#127]
It gave a few errors - it should close down gracefully.

Specifically, if a new engine is created and is in the process of being built (pending or active), the jobs should cancel before it is all deleted.  There may also be a need for a state "deleting" ... maybe...

**Comment by johnml1135** [comment]
The abbreviated error message showing the need:

```
Call failed with gRPC error status. Status code: 'NotFound', Message: 'The build does not exist.'.\n","stream":"stdout","time":"2023-09-11T16:18:29.255840722Z","type":"info","source":"Grpc.Net.Client.Internal.GrpcCall"}
POST http://serval-api:81/serval.translation.v1.TranslationPlatformApi/BuildFaulted\n","stream":"stdout","time":"2023-09-11T16:18:29.215850556Z","type":"info","source":"System.Net.Http.HttpClient.TranslationPlatformApiClient.LogicalHandler"}
POST http://machine-engine/serval.translation.v1.TranslationEngineApi/Delete\n","stream":"stdout","time":"2023-09-11T16:18:27.478076473Z","type":"info","source":"System.Net.Http.HttpClient.Nmt.ClientHandler"}
POST http://serval-api:81/serval.translation.v1.TranslationPlatformApi/BuildStarted\n","stream":"stdout","time":"2023-09-11T16:17:51.818285896Z","type":"info","source":"System.Net.Http.HttpClient.TranslationPlatformApiClient.ClientHandler"}
```

**Comment by johnml1135** [comment]
may be related to #121 - about things happening that aren't quite complete.

**Comment by johnml1135** [comment]
Or, we disallow deletion on an engine if there is an active build and tell the user to cancel the build first.

**Comment by ddaspit** [comment]
This sounds like a bug. I should cancel the build automatically.

**Comment by johnml1135** [comment]
So, will we also need a "deleting" state?  Or is that superfluous?  Once it is deleted, there is no expectation of it existing.  Yet, the cancelling and deleting may take 20 seconds to fully push through the whole system.  How should this be handled?

**Comment by johnml1135** [comment]
If that is the current behavior - then let's make sure that it is tested fully and I will be ok.  We should be able to do this with unit tests at the Machine level.  @ddaspit do you agree?

**Comment by ddaspit** [comment]
Yeah, sounds good.

**Comment by johnml1135** [comment]
To implement: Nmt and Smt test - delete the engine while the engine is building.  Unit tests in Machine.  May end up just being implemented in https://github.com/sillsdev/machine/pull/101.
