### ISSUE TITLE
Serval App

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#132]
Create a simple python application that can build NMT jobs and return pretranslations.  This app may be extended to be a bit more, but will always be a prototype/sample app.

Functional Requirements for MVP:
* Users receive a passcode from our team to be able to use the service
* Users are given a fair amount of instruction as to what is going on
* Users (without authentication beyond the passcode), enter:
  * An email address to send (1) confirmation of job started (2) an error if it errors out somehow and (3) the resultant translations
  * 2 paratext projects for training, one source and one target 
  * 1 or 2 paratext projects for translating (source needed, target optional)
  * Language codes for the source and target languages
  * Press a button to start and then tell them to check their email

Other Requirements for MVP:
* Similar to https://translator.multilingualai.com/
  * Uses https://streamlit.io/ (or is there a better one?)
* Use production Serval as backend - https://prod.serval-api.org/swagger/index.html
* We provide a passcode so that people can use it and share it in their groups, but that the internet in general does not have access
* Talk to Bryan Vold about getting an email to use.

Challenges post MVP:
* Instead of getting back json or text, can we recreate a paratext project?  Can we steal code from https://github.com/sillsdev/silnlp to do so?
*

**Comment by Enkidu93** [comment]
This looks very doable and right up my alley. (I miss python :stuck_out_tongue:). I imagine this would be best started in a fresh repo (???).

**Comment by ddaspit** [comment]
From a development perspective, the main benefit of using the Serval repo is that API changes and the corresponding changes to the web app could be made in the same PR.  It would be easier to keep Serval and the web app in sync. If the web app is built on a different tech stack (Python, streamlit, etc.), it can be tricky combine the build systems. I usually separate codebases if they are built on different languages and tech stacks. Machine is split into 3 repos: Machine.NET, Machine.py, and Machine.js. What about deployment? @johnml1135, how would separate repos affect deployment? I assume that the Serval web app would be deployed in our Kubernetes cluster.

**Comment by johnml1135** [comment]
The biggest concern would be separating the CI with both - but it actually can be done: https://stackoverflow.com/questions/63822219/how-to-run-github-actions-workflow-only-if-the-pushed-files-are-in-a-specific-fo.  

We can use streamlit for hosting the app - it should be free, because we will be publicly hosting the app:
![image](https://github.com/sillsdev/serval/assets/13733556/37b71c11-a67a-48db-84d5-931fef4db2a7)

It appears that it can be auto-deployed from a GitHub repo: https://docs.streamlit.io/streamlit-community-cloud/deploy-your-app

**Comment by Enkidu93** [comment]
> The biggest concern would be separating the CI with both - but it actually can be done: https://stackoverflow.com/questions/63822219/how-to-run-github-actions-workflow-only-if-the-pushed-files-are-in-a-specific-fo. Therefore, I recommend the mono-repo - add python to the serval repo.
> 
> We can use streamlit for hosting the app - it should be free, because we will be publicly hosting the app: ![image](https://user-images.githubusercontent.com/13733556/270056366-37b71c11-a67a-48db-84d5-931fef4db2a7.png)
> 
> It appears that it can be auto-deployed from a GitHub repo: https://docs.streamlit.io/streamlit-community-cloud/deploy-your-app

Sounds good :+1: . And yes, the CI shouldn't be an issue.

**Comment by ddaspit** [comment]
I'm fine with a monorepo approach.

**Comment by Enkidu93** [comment]
@johnml1135  @ddaspit See [here](https://github.com/sillsdev/serval/blob/serval_app_init/samples/ServalApp/REAME.md) my initial work - an absolute MVP.

The UI:
![image](https://github.com/sillsdev/serval/assets/83078660/269e7a48-e14c-4454-956b-434d073a0ace)

It sends emails to the address associated with the build when the build starts, faults or is canceled, and when it is finished - at which point it attaches a text file with the pretranslations that looks something like the following:
```
...

source.txt:verse_001_001	The book of the birth of Jesus Christ , the son of David , the son of Abraham .
source.txt:verse_001_002	Abraham was the father of Isaac, Isaac the father of Jacob, and Jacob the father of Judas and his brothers.
source.txt:verse_001_003	Judah begat Pharaoh and Sarah in Tamar; and Pharaoh begat Shoram; and Shoram begat Ram;
source.txt:verse_001_004	and Miriam the father of Minadab, and Minadab the father of Nahason, and Nahason the father of Salmon,
source.txt:verse_001_005	and Salmon begot Boaz of Ahab; and Boaz begot David of Judah; and David begot Jesse;
source.txt:verse_001_006	And in the same year was born David the king .

...
```

**Comment by johnml1135** [comment]
Instead of the passcode, use Serval Auth0 creds - and hard-code the production URL and Auth0 Token URL.
