### ISSUE TITLE
Filter by chapter in Paratext Projects

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#150]
Support chapter syntax? for filtering in textId's for Paratext Projects and individual USFM files:
Example filters:
* 1,2,3,6,7,11-20
* Do not assume that chapters will be increasing
* Do not assume that all chapters are in the book (be ok with 1-500)

For Paratext projects:
* MAT1, 2, 3. 5-11; MRK1-100; LUK; JON; ROM-REV
* MAT-REV;-LUK10-30

* Semicolons separate books, comas separate chapters
* Dashes can be used for books or chapters
  * Include a list of all books in Paratext order, including deuterocanonical books
* Book removals take precedence over adding
* Only individual books or portions of books can be removed at a time

For USFM files:
* MAT01.usfm1-20 -or- MAT1-20 (should be the same)

For getting pretranslations, instead of a textId field, make a textIdQuery field that can be separated by semicolons for separate textId's or use the MAT-REV syntax.

**Comment by Enkidu93** [comment]
Partially addressed here: https://github.com/sillsdev/machine/pull/132. Should we close this issue or keep it as a placeholder for filtering syntax, @johnml1135 ?

**Comment by ddaspit** [comment]
We should keep it open, since we haven't added chapter filtering yet.

**Comment by ddaspit** [comment]
This isn't quite in yet.
