### ISSUE TITLE
CI Tests in parallel across Serval/Machine

### ISSUE THREAD

**Issue by Enkidu93** [sillsdev/serval#153]
It would have been useful (and I imagine will continue to be) to have the ability to create parallel branches in Machine and Serval such that tests run on-push on these branches will use the matching branch from the other repo. For example, in the recent [issue](https://github.com/sillsdev/serval/issues/45) to do with config passing, all of our E2E tests were failing on pushes to the branch because changes done in a feature branch in machine were required. Maybe we could default to fetching a branch with the same name in Machine and if it does not exist, use `master`. Thoughts, @johnml1135?

**Comment by ddaspit** [comment]
Don't you need to publish a docker image for Machine before you can use it in Serval E2E tests? Also, I would rather keep E2E tests manual on PRs.

**Comment by johnml1135** [comment]
You can pull the master branch in an adjacent folder and run docker-compose:
```
      - name: Get Serval
        run: dotnet build && cd .. && git clone https://github.com/sillsdev/serval.git && cd serval && dotnet build

      - name: Start containers
        run: docker compose -f "../serval/docker-compose.yml" up -d && sleep 20 #allow time for mongo to start up properly
```

**Comment by johnml1135** [comment]
Actually - we should not use an adjacent folders for Serval and machine - see https://github.com/sillsdev/serval/issues/158.

**Comment by Enkidu93** [comment]
I think in this case, we could use adjacent folders because the point is to have two compatible versions of serval and machine. Isn't that right?
