### ISSUE TITLE
Serval NMT job responsiveness while building an SMT job

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#154]
How slow will the job server be if a SMT whole Bible is building?  Will NMT jobs be able to be prepared and scheduled in a timely manner?  Let's test it out and grab a few logs to see if it is "acceptable" - whatever that is.

**Comment by johnml1135** [comment]
We can test this on internal QA or docker-compose with limited CPU's for the job server.

**Comment by Enkidu93** [comment]
@johnml1135 What would be a realistic memory limit?

**Comment by johnml1135** [comment]
The current machine-job server has 2.5GB of RAM to work with.  We are also altering if memory of any pod is over 80%.

**Comment by Enkidu93** [comment]
I've tested responsiveness with docker-compose limited to 2.5GB of RAM. Response times were about doubled when an SMT whole bible job was builidng (as compared to when no SMT build job was building). But even these doubled response times were under 30 milliseconds. @johnml1135, is that sufficient?

**Comment by johnml1135** [comment]
Absolutely!
