### ISSUE TITLE
Decouple Kubernetes/Docker config from Machine config

### ISSUE THREAD

**Issue by ddaspit** [sillsdev/serval#157]
Currently, the Kubernetes and Docker configurations are heavily coupled to the configuration for Machine, an external dependency. It would be good if the Machine config could be completely self-contained in the Machine repo, so that changes wouldn't require commits to both repos. Secrets could be handled through environment variables that aren't tied to the Machine config structure.

**Comment by johnml1135** [comment]
The hard part with that is that similar to using MongoDB, if the API or configuration file changes, the MongoDB configuration in the docker image or the k8s charts also need to change.  I don't know a meaningful way of being able to hide the changes only in the machine repo.

**Comment by ddaspit** [comment]
The appsettings feature in ASP.NET Core supports multiple deployment environments. All of the configuration for different environments could be contained in the appsettings files in the Machine repo. That would leave secrets. These could be set using environment variables that are not tied to the Machine configuration structure. This would allow us to freely make changes to the Machine configuration structure without having an impact on Serval.

**Comment by ddaspit** [comment]
The key issue is that the Serval deployment config is currently too coupled to the configuration structure of an external dependency. There are definitely ways that we can reduce the coupling, so that in most cases making changes to external dependency's configuration structure won't break Serval deployment. The design I proposed in a previous comment is just an example of how this could be done.

**Comment by johnml1135** [comment]
I have been thinking about this a bit more and here is what I think most deployable software does and what we should do:
* Have a few different "modes of operation" such as development, production and quick_test (may be enough)
* All network topology parameters stay in k8s files including:
  * Docker images of machine.py
  * ClearML connection params (URL + queue)
  * Serval callback URL
* These network topology parameters are defined in a stable way that doesn't change even if the underlying Machine implementation changes (it is in essence, a network API)
* We specify in the Machine readme what parameters are needed to connect it with the outside world

Rationale:
* We need flexibility to change the network topology of a Serval deployment without rebuilding machine
* Machine's few "modes of operation" (production, development, quick-test) can be built in - but then we should be able to switch between them
* The entire network topology can be defined in one place, the Serval k8s charts

**Comment by johnml1135** [comment]
We could call the 3rd state a `dummy_build`.  It implies that it goes through the real pipeline, but that somehow, it is all fake and that no good data could come from it.  @ddaspit, can we also make a `dummy_build` for SMT?  It would be nice to try out large files for training, but only do 1 step of the training for speed.  We can pass `dummy_build` to Machine.py as per https://github.com/sillsdev/serval/issues/178 as well.

**Comment by johnml1135** [comment]
Proposed params to consolidate into development and dummy_build appsettings (internal config):
* app_settings:
  * ASPNETCORE_Logging__LogLevel__Default=Information
  * ASPNETCORE_Logging__LogLevel__Microsoft.AspNetCore=Warning
* specific to machine:
  * ASPNETCORE_TranslationEngines__0=SmtTransfer
  * ASPNETCORE_TranslationEngines__1=Nmt
* machine.py dummy_build:
```
dummy_build:
  max_steps: 10
  huggingface:
    parent_model_name: facebook/nllb-200-distilled-600M
    generate_params:
      num_beams: 1
```

Proposed params to leave as env variables (networking topology):
* ASPNETCORE_ENVIRONMENT=dummy_build
* ASPNETCORE_Kestrel__Endpoints__Grpc__Url
* ASPNETCORE_Kestrel__Endpoints__Grpc__Protocols
* ASPNETCORE_ConnectionStrings__Hangfire
* ASPNETCORE_ConnectionStrings__Mongo
* ASPNETCORE_ConnectionStrings__Serval
* For Serval:
  * All ASPNETCORE_Translation__Engines endpoints (they can change with deployment - include the echo or no?)
* For Machine:
  * All ClearML and S3 configs

**Comment by ddaspit** [comment]
I think that makes sense. Maybe we could move all of the connection strings under `ASPNETCORE_ConnectionStrings`. That would provide us with a stable and clearly demarcated configuration section that would require changes to the Kubernetes deployment if it changed. All of the rest of the configuration could be changed without breaking the deployment.

**Comment by johnml1135** [comment]
I'm ok with the layout right now.  Apart from the ClearML / NMT change, they have been very stable.

**Comment by johnml1135** [comment]
This has been implemented to the extent that it will be.
