### ISSUE TITLE
Issues with the API

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#16]
* What happens if I queue up multiple builds from one engine at the same time?  Is it possible?  It should say "I'm Sorry Dave, I'm Afraid I Can't Do That".  If not, how do I cancel anything but the current build?
* Can I upload the same file into multiple corpora on one engine?  (say, use half of Luke to build the model, but pretranslate the whole thing)? Will there be a file conflict - or do they get new names when put onto s3 bucket for nmt or use the mounted volume for SMT?  We should be able to.
* Data should be forever - until it isn't.  If it is not there (and it should have been) Serval should give an error saying "this doesn't exist" or "the data is corrupted - remake the engine".
* Explain the format of a pretranslation better - what are refs?
* The flow of: (1) load files; (2) build engine; (3) get pretranslation; (4) upload updated files;  (5) build again; (6) get more pretranslations should be more explicit.
* Should be able to patch a corpus. otherwise, when deleting a corpus to associate new files, the pretranslations will be deleted! #17 #23
* On files and corpora (which should be able to be patched), they should have either a revision or a "last updated date" date or both. #18
* Pretranslations should say which build they were generated from and not be modified until overwritten by a new pretranslation of that specific verse reference from the new build. #25 
* Webhooks need an explanation of how to use them and an example

**Comment by ddaspit** [comment]
Only one build is allowed at a time on an engine. If you start a new build while a build is currently running, then the current build will be automatically canceled.

**Comment by ddaspit** [comment]
I'm going to close this issue. Please create separate issues for any remaining work.
