### ISSUE TITLE
SF: Project admin can override the language codes used by Serval for the source and target

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#161]
Issue 3: https://docs.google.com/spreadsheets/d/13Y8d3z3JajAoR2B1zDbsjb0q_GLVQaB6iX9rZPM9it4/edit#gid=0

**Comment by johnml1135** [comment]
Guidance for user in UI: the language for the training source and the pretranslation source must be the same.
Admin UI: Allow overriding the source and target language code that will be used by Serval - and call out the [NLLB language codes](https://github.com/facebookresearch/flores/tree/main/flores200#languages-in-flores-200) as recommended for sources.

**Comment by pmachapman** [comment]
See https://jira.sil.org/browse/SF-2624
