### ISSUE TITLE
SF: Selection of books of the Bible to be used for training

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#163]
Issue 5 here: https://docs.google.com/spreadsheets/d/13Y8d3z3JajAoR2B1zDbsjb0q_GLVQaB6iX9rZPM9it4/edit#gid=0

**Comment by pmachapman** [comment]
This is being developed in [SF-2278](https://jira.sil.org/browse/SF-2278).

**Comment by pmachapman** [comment]
The backend component of this is being developed in [SF-2288](https://jira.sil.org/browse/SF-2288).
