### ISSUE TITLE
SF: Send Key Biblical Terms to Serval as training data

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#167]
See issue 13 here: https://docs.google.com/spreadsheets/d/13Y8d3z3JajAoR2B1zDbsjb0q_GLVQaB6iX9rZPM9it4/edit#gid=0

**Comment by pmachapman** [comment]
This was developed in [SF-2258](https://jira.sil.org/browse/SF-2258) and merged in sillsdev/web-xforge#2091.
