### ISSUE TITLE
The build options passed to the start build endpoint should be arbitrary JSON

### ISSUE THREAD

**Issue by ddaspit** [sillsdev/serval#180]
Currently, the build options in `TranslationBuildConfigDto` is a string. This should hold arbitrary JSON and not a string.

**Comment by johnml1135** [comment]
I'm assuming it should be a `JsonObject` then.

**Comment by Enkidu93** [comment]
Yeah, this shouldn't be a problem. We discussed it earlier, but it wasn't a top priority. I can go ahead and take care of this.

**Comment by ddaspit** [comment]
It might be tricky getting this to work with NSwag.

**Comment by Enkidu93** [comment]
Yeah, that's the difficult part - that's why it wasn't done initially. I'm investigating though.
