### ISSUE TITLE
Clarify language code documentation for NLLB

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#182]
It roughly says what we want, but we should do a few things:
* In all places, point people to engine creation for more documentation on language codes
* In engines, for language codes, say "See engine type for more information"
* For NMT, say something to the effect:
> If you use a code from the [NLLB-200 list](https://github.com/facebookresearch/flores/tree/main/flores200#languages-in-flores-200), Serval will utilize everything the NLLB-200 model already knows about that language when doing the translation.  If you use an [IETF language tag](https://en.wikipedia.org/wiki/IETF_language_tag), Serval will convert it to a NLLB-200 code.  If the language you are working with is not in the NLLB-200 model, any language code that is not in the NLLB-200 list can be chosen as name will have no effect.  When possible, the use of  IETF language tags are recommended.

**Comment by johnml1135** [comment]
This issue is coming about because of frequent questions about how to use language codes.

**Comment by Enkidu93** [comment]
I'm going to take care of this now. I would lean toward it not being necessary to mention defaulting to simplified Chinese. As a user, I would have assumed it would default to simplified characters. Unless we expect to have numerous language projects working out of Taiwan (and I know there are a handful of un-Bibled, indigenous languages there still), I don't see the question of how to use traditional characters even coming up.

**Comment by johnml1135** [comment]
Good enough for now.
