### ISSUE TITLE
Serval API is configured with the wrong audience on Auth0

### ISSUE THREAD

**Issue by ddaspit** [sillsdev/serval#193]
On Auth0, `Serval API` is configured with `https://machine.sil.org` as the audience. This should be updated to `https://serval-api.org`. In addition, there is an unnecessary "Machine to Machine" application setup for Scripture Forge called `SF to Serval Production`. SF already has a "Machine to Machine" application called `Scripture Forge Backend`. The `Serval API` should be authorized for the `Scripture Forge Backend` application.

**Comment by ddaspit** [comment]
I have created a new `Serval API` that has the correct audience in the production Auth0 tenant. I authorized the `Scripture Forge Backend` application to use it with all scopes. We need to notify the SF team of the new audience. Once, they have updated their code, we can remove the old API and application. We should probably do the same for the other tenants.

**Comment by ddaspit** [comment]
I've updated the staging tenant as well.

**Comment by ddaspit** [comment]
The `Allowed Web Origins` and `Allowed Origins (CORS)` settings in Auth0 should not be needed for client credentials flow. I removed them on the `Serval Swagger` client on the development tenant and Swagger still works. Let's try removing them for the E2E tests as well. If that works, then we can remove them on all clients.

**Comment by ddaspit** [comment]
I tested the E2E tests without the `Allowed Web Origins` and `Allowed Origins (CORS)` settings and it works.

**Comment by ddaspit** [comment]
@johnml1135 Have we migrated everything over to the new audience?

**Comment by johnml1135** [comment]
As for `Allowed Web Origins` and `Allowed Origins (CORS)`, I think they were likely needed when the audience was not set correctly (and will continue to be needed for `localhost`, etc.).

All have been transitioned to the new audience and all users have been notified.
