### ISSUE TITLE
Language Tag Conversion Intermittently Failing

### ISSUE THREAD

**Issue by Enkidu93** [sillsdev/serval#194]
Recreate: Pretranslate source text file in English (IETF tag "en") to Chinese (zh). Job fails with trace:

```
machine-job-cntr     | fail: SIL.Machine.AspNetCore.Services.NmtPreprocessBuildJob[0]
machine-job-cntr     |       Build faulted (6537d23d973458139440c908)
machine-job-cntr     |       System.NullReferenceException: Object reference not set to an instance of an object.
machine-job-cntr     |          at SIL.Machine.AspNetCore.Services.NmtClearMLBuildJobFactory.ConvertLanguageTag(String languageTag) in /home/enkidu/SILdev/machine/src/SIL.Machine.AspNetCore/Services/NmtClearMLBuildJobFactory.cs:line 74
machine-job-cntr     |          at SIL.Machine.AspNetCore.Services.NmtClearMLBuildJobFactory.CreateJobScriptAsync(String engineId, String buildId, String stage, Object data, String buildOptions, CancellationToken cancellationToken) in /home/enkidu/SILdev/machine/src/SIL.Machine.AspNetCore/Services/NmtClearMLBuildJobFactory.cs:line 40
machine-job-cntr     |          at SIL.Machine.AspNetCore.Services.ClearMLBuildJobRunner.CreateJobAsync(TranslationEngineType engineType, String engineId, String buildId, String stage, Object data, String buildOptions, CancellationToken cancellationToken) in /home/enkidu/SILdev/machine/src/SIL.Machine.AspNetCore/Services/ClearMLBuildJobRunner.cs:line 51
machine-job-cntr     |          at SIL.Machine.AspNetCore.Services.BuildJobService.StartBuildJobAsync(BuildJobType jobType, TranslationEngineType engineType, String engineId, String buildId, String stage, Object data, String buildOptions, CancellationToken cancellationToken) in /home/enkidu/SILdev/machine/src/SIL.Machine.AspNetCore/Services/BuildJobService.cs:line 102
machine-job-cntr     |          at SIL.Machine.AspNetCore.Services.NmtPreprocessBuildJob.DoWorkAsync(String engineId, String buildId, IReadOnlyList`1 data, String buildOptions, IDistributedReaderWriterLock lock, CancellationToken cancellationToken) in /home/enkidu/SILdev/machine/src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs:line 36
machine-job-cntr     |          at SIL.Machine.AspNetCore.Services.NmtPreprocessBuildJob.DoWorkAsync(String engineId, String buildId, IReadOnlyList`1 data, String buildOptions, IDistributedReaderWriterLock lock, CancellationToken cancellationToken) in /home/enkidu/SILdev/machine/src/SIL.Machine.AspNetCore/Services/NmtPreprocessBuildJob.cs:line 47
machine-job-cntr     |          at SIL.Machine.AspNetCore.Services.HangfireBuildJob`1.RunAsync(String engineId, String buildId, T data, String buildOptions, CancellationToken cancellationToken) in /home/enkidu/SILdev/machine/src/SIL.Machine.AspNetCore/Services/HangfireBuildJob.cs:line 70

```

If you do something similar with French, Spanish, etc., there's no issue. Originally, I thought it might be an issue with the `SIL.WritingSystems` library because I noticed they had fixed some things to do with the "zh" tag a while back. But debugging the issue, it appears that the source and target language tags for the engine are the empty string. I don't understand how this is even possible that it would fail on Chinese but not French, for example, when, to my knowledge, this is the first place it really interacts with the tag. 

We've seen this error a few times on the Grafana alerts (before the recent build job refactor as well) under similar conditions I imagine.

**Comment by Enkidu93** [comment]
@ddaspit @johnml1135, any thoughts?

**Comment by johnml1135** [comment]
I don't know what it could be.

**Comment by ddaspit** [comment]
When it comes to language tags, Chinese is tricky. The language code for Chinese ("zh") is ambiguous for a writing system, because Chinese has two scripts: Simplified and Traditional. As a result, "zh" is almost never used alone. It is typically used with the region code. For example, Simplified Chinese is usually specified as "zh-CN" and Traditional Chinese is usually specified as "zh-TW".  The `scriptSubtag` is `null`, which is causing the crash. We should gracefully handle this case.

**Comment by Enkidu93** [comment]
Right. That makes sense. It seems odd to me that they wouldn't just default to one or the other (probably simplified given the number of Mandarin speakers using simplified to traditional). Seems a mite political haha.
