### ISSUE TITLE
Filter on Bible books for Paratext Projects for model training

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#202]
Through Text ID's.

**Comment by johnml1135** [comment]
And add necessary comments in Swagger and link to https://github.com/sillsdev/serval/wiki/Versification-in-Serval.

**Comment by johnml1135** [comment]
To keep it simple for MVP - let's just have a list of textId's (vrs 3 character names) for the included books.  Later we can implement the same parsing as is done in SILNLP in a different ticket.

**Comment by Enkidu93** [comment]
Should this work for text corpora as well as Paratext projects (I realize there's less of a need for it, but should it work universally?)? I'm imagining an additional field in the start build request with a list of textIds/book refs for training.

**Comment by johnml1135** [comment]
For Paratext projects only.  Text corpora are up to the user to do.

**Comment by Enkidu93** [comment]
OK. So make the field do nothing if it's a text corpus? (I could see some benefit in having the same functionality for text corpora because you could try multiple arrangements of hold-outs given one corpus and it'd be more unified).

**Comment by johnml1135** [comment]
The textId for text corpora is for the actual textId - the really long unique ID.  What we would in essence be saying is that if it were a text file, we could have a large <or> filter on labels by overloading the textId field.  I don't see why not - as long as it is documented.

**Comment by Enkidu93** [comment]
I'm not sure I understand this comment. The textIds are always user defined textIds (or the book names for Paratext projects), not the fileIds or corpusIds etc. which are the long strings (???).

I'm thinking something like this: 
```
{
  "name": "trainOnSynopticsOnly",
  "train_on": [
    {
      "corpusId": "************************",
      "textIds": [
        "MATT_1", #These are textIds from pairs of text files like what SF is using now.
        "MATT_2",
        ...,
        "LUKE_24"
      ]
    }
  ],
  "pretranslate": [ ]
  "options": {
    "max_steps": "10000"
  }
}
``` 
I'm just thinking that if someone already has a text corpus defined (say all existing materials), they can now reuse that corpus but experiment with different training data (given someone uploads chapter by chapter, they can even train now on specific chapters). It seems to me that supporting a "train_on" parameter using textIds for Paratext corpora but not for text corpora (when I can't imagine it'd be terribly difficult to support both) is odd. 

I'm just wondering if supporting the above in parallel

**Comment by Enkidu93** [comment]
Thoughts @johnml1135 ?

**Comment by johnml1135** [comment]
There are a few different ways to go, some that might be great technically, but may not actually be needed by the users.  The type of filtering for labels would likely be a nice regular expression while the filtering for Paratext projects would likely be a Bible-centric query language that understands the books available (i.e., GEN:REV-MAT).  Long term, the `text` format will be used primarily for non-scripture and `Paratext` format for scripture.  Since there is no request for filtering on labels and there is a need to filter within paratext projects here is a proposal:
* Add a new field called `paratextFilter`? `bookId`? `bibleFilter`? that can take a string that to start, can be a semicolon separated list of books.  Note that we may start having book references, i.e., `MAT 1,2,5-10` that would have spaces, colons, commas and dashes.  Semicolons should be unique.
* This should allow the most easy, basic usage (a semicolon separated list of Bible books for when SF uses Paratext zip files) and expand to more advanced usage.
* If we choose this means, we should likely change the filter for pretranslations as well

@ddaspit,  do you have any thoughts?
