### ISSUE TITLE
SF: Validation run button

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#203]
When a project is being onboarded and the super-admin is setting everything up, they should have an option to run a validation run that will:
* Add a few extra things to the Serval options for the build (specifically, to use the [validation split](https://github.com/sillsdev/machine.py/issues/54) to get a good bleu score).
* Otherwise, use the configuration as it is currently setup to use
* Display the final message from the build - this will be a [build summary](https://github.com/sillsdev/machine.py/issues/53) and can help the super admin finalize the configuration

**Comment by ddaspit** [comment]
We don't have a specific requirement for this, so I am putting this on the backlog.

**Comment by pmachapman** [comment]
See https://jira.sil.org/browse/SF-2628
