### ISSUE TITLE
Which versification is used?

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#208]
In different versifications, some portions of scripture are in different books.  For instance Bell and the Dragon may be a separate book or part of Daniel.  If there are different versifications, we need to choose a specific versification to apply.   This brings us to our two questions:
* Which versification is used in the pretranslations received
* Which versification is used for filtering books (and potentially chapters)
* What is versification - let's document it.

### Versification for pretranslations
  Part of the magic of Serval is that the clients don't have to think about versification.  To enable this, the versification of the pretranslations should really be the target versification, as per the target Paratext project (even if it is empty).  That is, all the labels applied should be rewritten to the target versification.
* As of note, it may be worthwhile to add another variable when getting the pretranslations to choose one of three versificaitons: target; source; original, and default to target.

### Versification of filtering
 While there is usually only one pair of Paratext projects used now, in the future there may be multiple diverse versions of the Bible used for training.  Therefore, the most straightforward way of filtering would be to use original versification - and document it and be explicit about it.

### Document versification
  This will probably be a new wiki page and some links to it.  If there is something that already exists, let's just use that.  The only existing things found online are:
* https://github.com/sillsdev/scripture
* https://github.com/sillsdev/libpalaso
Neither of which really describe what versification is, the main contours of it, what "original versification" actually means, etc.  Possibly the Wiki for this should end up on libpalaso's wiki.

**Comment by johnml1135** [comment]
Versification documentation is found here:
* A brief description of the main versificaitons: https://github.com/Copenhagen-Alliance/versification-specification/blob/master/versification-mappings/standard-mappings/README.md
* The main VRS files: https://github.com/ubsicap/versification_json/tree/master/examples

We probably should still make a Wiki entry about how Versification works in Serval - referencing these other resources.

**Comment by Enkidu93** [comment]
Not to be insensitive to those using less common versifications, but do we have any stats here on the usage of these versifications? I would think that an overwhelming majority of our users would be using the same versification. Certainly, there will be book-level discrepancies between the Catholic/Eastern/Oriental/Reformed Bibles, but I was under the impression that (with the exception of Orthodox OTs which are LXX-based) most folks were using the cross-confessional versification popular in English bibles anymore. I just wouldn't want us to go overboard with information if this isn't such a big issue. It would be easier to scope if we had some stats on what folks are really needing.

**Comment by johnml1135** [comment]
Potential wording for Swagger documentation for filtering:
### Versification for Filtering Books
Paratext projects can be filtered by book for training and pretranslating.  This filtering follows the [original versification](https://github.com/ubsicap/versification_json/blob/master/examples/org.vrs).  To filter, use the 3 character code for the book of the Bible in the textID while building.

**Comment by johnml1135** [comment]
Wiki page to document Versification: https://github.com/sillsdev/serval/wiki/Versification-in-Serval

**Comment by johnml1135** [comment]
As for versification of pretranslations, we already use the target versification in machine.py.  Let's just keep using it and document it in Swagger - and not give the option for other versifications.

**Comment by johnml1135** [comment]
For filtering versification, let's just use the target versification because (1) the user is most familiar with it and (2) when the corpora are aligned, only the source and target versifications are easily accessible.

**Comment by johnml1135** [comment]
To resolve this issue, a comment needs to be added to Serval giving a very brief overview of Versification when posting a Paratext file (see above) and reference the wiki page.
