### ISSUE TITLE
Queue Depth discrepancies

### ISSUE THREAD

**Issue by pmachapman** [sillsdev/serval#212]
I have noticed some discrepancies in how the queue depth works:

**A. The queue depth appears to be 1 lower than the actual queue depth**
See screenshots 1 and 2. Should the queue depth include the first in the queue? i.e. If one build is running, and the second is pending, the second build should return a queue depth of 1, while currently it returns 0.

I could just increment this on display, but I how would I know when the queue depth is actually 0?

**B. Sometimes the queue depth gets stuck**
See screenshot 3. I noticed this after I queued the 4 builds, 1 had run and 1 had failed, so this potentially happened because the build failed? (details in JSON 4 below). I am not too worried about the failure as I think the build was just too big for QA? (The build was NIV11 plus a 2 completed books and a 2/3 canon, English to French)

**Screenshot 1: 3 projects building**
![3_Projects](https://github.com/sillsdev/serval/assets/8665431/f828fb5a-6bb1-45e1-9f83-f5c88f5c8370)

**Screenshot 2: 4 projects building**
![4_Projects](https://github.com/sillsdev/serval/assets/8665431/672b82de-b429-44a1-a252-fdee5494d6e3)

**Screenshot 3: Queue Depth stuck**
![Stuck](https://github.com/sillsdev/serval/assets/8665431/2a26d314-cbcc-4829-8e0d-c6913fac98af)

**JSON 4: Failed build details:**
```json
  {
    "id": "6549365c3627520aa518250b",
    "url": "/api/v1/translation/engines/654934193627520aa518183e/builds/6549365c3627520aa518250b",
    "revision": 6,
    "engine": {
      "id": "654934193627520aa518183e",
      "url": "/api/v1/translation/engines/654934193627520aa518183e"
    },
    "pretranslate": [
      {
        "corpus": {
          "id": "654936503627520aa518250a",
          "url": "/api/v1/translation/engines/654934193627520aa518183e/corpora/654936503627520aa518250a"
        }
      }
    ],
    "step": 0,
    "percentCompleted": 0,
    "message": "OutOfMemoryError : CUDA out of memory. Tried to allocate 2.93 GiB (GPU 0; 23.69 GiB total capacity; 15.76 GiB already allocated; 2.85 GiB free; 19.82 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF",
    "queueDepth": 0,
    "state": "Faulted",
    "dateFinished": "2023-11-06T19:30:19.545Z",
    "options": {}
  }
```

**Comment by Enkidu93** [comment]
Hey, @pmachapman!

A. Yep, that's a good point. That was an intentional numbering on my part - somehow depth 0 made sense to me as being in the front of the queue, but I see how that makes differentiating running builds from queued ones difficult (although I imagine you could just use the status in combination with the depth?). I'm happy to update that if you like.

B. I think the issue might be the order of our filtering. We were discounting faulted builds (or trying to), but I think I see how we might be reintroducing them. I can take care of that too.

Also, just checking: Did you see the note in swagger (which exists because I also found it a bit misleading) that the percent complete is a value between 0 and 1 not 0 and 100?

**Comment by pmachapman** [comment]
Sounds good - thank you!

> Did you see the note in swagger (which exists because I also found it a bit misleading) that the percent complete is a value between 0 and 1 not 0 and 100?

I must have missed it for some reason. Thanks for identifying that bug!

**Comment by Enkidu93** [comment]
@pmachapman I'm not seeing at a glance what may have caused the 'stuck' issue. Just wondering: Did you recheck the queue depth after a couple minutes? The depths etc. are cached briefly. I'm guessing this wasn't the issue given you had up-to-date status information on the others, but it's possible depending on the order of events and your method for polling the queue depth.

**Comment by Enkidu93** [comment]
> @pmachapman I'm not seeing at a glance what may have caused the 'stuck' issue. Just wondering: Did you recheck the queue depth after a couple minutes? The depths etc. are cached briefly. I'm guessing this wasn't the issue given you had up-to-date status information on the others, but it's possible depending on the order of events and your method for polling the queue depth.

@pmachapman Any thoughts here?

**Comment by pmachapman** [comment]
@Enkidu93 I will let you know when I am able to look into this early next week (I am away from my desk). Caching sounds likely to be the answer, but I will need to investigate a bit more.

**Comment by pmachapman** [comment]
@Enkidu93 Definitely appears to be caching - the values update after a minute or so. I don't think that will be a problem on production given the build times will be much longer there than the reduced `max_depth` on QA.
