### ISSUE TITLE
Filtering errors is not working

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#214]
We gave 100's of 503 - but no errors were logged as per `ErrorResultFiter.cs`.  What gives?

See no error logs:
`{namespace="serval", container!="mongo"}  | json  | line_format "{{.app}}: {{.time}} {{.log | trunc 1000}}" |= "Serval responded with code"`

See errors:
http_server_duration_milliseconds_sum{http_status_code=~"5.*"}

**Comment by ddaspit** [comment]
Here is a relevant quote from the [ASP.NET Core documentation](https://learn.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-7.0#iresultfilter-and-iasyncresultfilter):

> Result filters are only executed when an action or action filter produces an action result. Result filters are not executed when:
> - An authorization filter or resource filter short-circuits the pipeline.
> - An exception filter handles an exception by producing an action result.

**Comment by johnml1135** [comment]
Here is documentation on trying to generally capture all exceptions: https://learn.microsoft.com/en-us/aspnet/web-api/overview/error-handling/web-api-global-error-handling.  It appears that a Result filter is not the one we want.

**Comment by ddaspit** [comment]
It looks like that link refers to legacy ASP.NET. We probably want to use [IAlwaysRunResultFilter/IAsyncAlwaysRunResultFilter](https://learn.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-7.0#ialwaysrunresultfilter-and-iasyncalwaysrunresultfilter).

**Comment by Enkidu93** [comment]
Alrighty, so I pushed the simple fix to log on 503s, but I'm not confident that that will be helpful in this case. If the entire machine-job-cntr crashes, I don't see how this would register the issue. Can we set up some logic on rancher to save the end of the logs when a container crashes?

**Comment by Enkidu93** [comment]
@johnml1135 @ddaspit

**Comment by ddaspit** [comment]
This should be sufficient. Serval calls the GetWordGraph gRPC endpoint on the Machine engine. This call causes a segmentation fault in the Machine engine, which crashes the process. As a result, the gRPC request fails and throws and exception. This results in the 503 from Serval. The main piece of information we need is the engine ID for the original GetWordGraph request to the Serval API. This fix should cause that information to get logged when Serval returns a 503.

**Comment by ddaspit** [comment]
@Enkidu93 Did you test out the change to ensure that the log entry is being written when an exception is thrown?
