### ISSUE TITLE
Consider making the health check endpoint private

### ISSUE THREAD

**Issue by ddaspit** [sillsdev/serval#223]
The health check endpoint could provide useful information to a hacker. We should consider making it private in order to increase security.

**Comment by johnml1135** [comment]
Yet to have any external service monitor and alert us if it is unhealthy, or to be able to query it ourselves, we would need it exposed.  The /metrics endpoint that Prometheus scrapes is hidden:
https://github.com/sillsdev/serval/blob/c0626239f11dc215067eeae583a577a3e591555b/deploy/serval/templates/serval-ingress.yaml#L26-L32

I would recommend to keep it external - the architecture of Serval is exposed through this repo (and the deployment scripts) and a healthy/unhealthy status would not give much aid to adversaries, but help us quickly see if something is wrong.

**Comment by ddaspit** [comment]
@pmachapman, you originally suggested making it private. Can you provide your reasoning for this suggestion, so we can make an informed decision? Thanks.

**Comment by johnml1135** [comment]
Here is an option from [this post](https://stackoverflow.com/questions/54362223/integrating-healthcheck-endpoint-into-swagger-open-api-ui-on-dotnet-core):
* Make a new  controller "healthController"
* Add an endpoint on that location
* Make it a separate permission
* Create a credential that can just access that endpoint that can see the health (for 3rd party services, etc.)

**Comment by johnml1135** [comment]
@pmachapman and @Nateowami - when we convert any health checks that you perform to using the new endpoints, I can remove the health check endpoint from being public.

**Comment by Nateowami** [comment]
@johnml1135 I'm quite confident we're not using any health endpoints.
