### ISSUE TITLE
Clarify note on train-segment "sentence start"

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#224]
"What does SentenceStart do"?  This should be fixed.

**Comment by ddaspit** [comment]
It isn't used for NMT models, but it is used for SMT suggestions. @Enkidu93 is correct. It is used to indicate that a segment is the start of a sentence. It is used when training a truecasing model (case restoration).

**Comment by Enkidu93** [comment]
> It isn't used for NMT models, but it is used for SMT suggestions. @Enkidu93 is correct. It is used to indicate that a segment is the start of a sentence. It is used when training a truecasing model (case restoration).

OK, yes! That makes perfect sense then.
