### ISSUE TITLE
Include Keyterms from Paratext Project in Training Data with toggle

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#225]
This issue is forked off of #52.
SF currently has an implementation to extract keyterms and send the files to Serval for training.  This issue is to implement this functionality directly into Serval and Machine.  It will:
* Implement the following algorithm in Machine (as per SILNLP)

``` python
def _process_gloss_string(gloss_str: str) -> List[str]:
    match = re.match(r"\[(.+?)\]", gloss_str)
    if match is not None:
        gloss_str = match.group(1)
    gloss_str = gloss_str.replace("?", "")
    gloss_str = clean_term(gloss_str)
    gloss_str = strip_parens(gloss_str, left="[", right="]")
    gloss_str = re.sub(r"\s+\d+(\.\d+)*$", "", gloss_str)
    glosses = re.split("[;,/]", gloss_str)
    glosses = unique_list([gloss.strip() for gloss in glosses if gloss.strip() != ""])
    return glosses
```

* Add a training pair per gloss
* Create a new field when building an engine to include paratext keyterms or not
  * We may be able to hack the "options" field in builds and then document how to use it.  i.e., `paratext_parsing -> use_keyterms_for_training=true`
  * Default to true (use the keyterms)
* [Add a test] Make sure that the response message from Serval only includes `paratext_parsing` options that are accepted (as a way to communicate whether they are properly formatted or not).  For other options (not `paratext_parsing`), Machine doens't know what Machine.py would accept.

**Comment by Enkidu93** [comment]
I've followed the implementation in SILNLP, but it's still not clear to me where I'm getting source and target data??? @ddaspit @johnml1135

**Comment by johnml1135** [comment]
Example:
* Keyterm: glosses
* Hello: Hola Caramba Bueno

The output would be:
| source | target |
| ----------- | ----------- |
| Hello | Hola       |
| Hello | Caramba        |
| Hello | Bueno        |

**Comment by Enkidu93** [comment]
OK, but my question is, will the glosses always be in the source language? @johnml1135

**Comment by Enkidu93** [comment]
Also, @ddaspit , should we use the Category element within each term to ignore everything but proper nouns (if that's a universal categorization)? I know you mentioned in the related ScriptureForge issue that you thought only proper nouns would be helpful.

**Comment by Enkidu93** [comment]
@ddaspit What's the point of this:
```
    match = re.match(r"\[(.+?)\]", gloss_str)
    if match is not None:
        gloss_str = match.group(1)
```
I know what it does, but I can't seem to find an example of a key terms xml that uses a format in which this would be needed. And it causes problems in situations in which there's a note in square brackets. What am I missing? Is there an expectation of some kind of preprocessing?

**Comment by Enkidu93** [comment]
OK, after digging into silnlp more, I think I'm not actually capturing the process. SILNLP uses the term renderings in conjunction with the biblical terms xml. Is that what SF is doing too, @pmachapman ?  What should we do here, @ddaspit ?

**Comment by pmachapman** [comment]
> Is that what SF is doing too?

SF just iterates over the Term Renderings, and uses the Id as the key: https://github.com/sillsdev/web-xforge/blob/3da7dfe8804d3121ec6b05c703790f8a4ebc5c84/src/SIL.XForge.Scripture/Services/SFBiblicalTermsText.cs#L111-L138

@Enkidu93 What information were you wanting to use from the Biblical Terms XML file?

Retrieving the BT XML file can be complicated to get, as most often one of the files chipped with PT will be used, sometimes the BT file will be in the project, sometimes it will be in another project.

**Comment by Enkidu93** [comment]
> > Is that what SF is doing too?
> 
> SF just iterates over the Term Renderings, and uses the Id as the key: https://github.com/sillsdev/web-xforge/blob/3da7dfe8804d3121ec6b05c703790f8a4ebc5c84/src/SIL.XForge.Scripture/Services/SFBiblicalTermsText.cs#L111-L138
> 
> @Enkidu93 What information were you wanting to use from the Biblical Terms XML file?
> 
> Retrieving the BT XML file can be complicated to get, as most often one of the files chipped with PT will be used, sometimes the BT file will be in the project, sometimes it will be in another project.

OK, thank you! Very good to know. After speaking with Damien, for the time being, if both projects have BT xmls, we'll use those aligning on the term id. Later, we might add a method of incorporating the data from the TR xmls like what SF currently has.
