### ISSUE TITLE
Get USFM endpoint

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#242]
Instead of JSON, can we get USFM per book (when there are parallel Paratext project inputs). 
* Mimic the behavior of SILNLP
* For verses 

Option 1: use the source USFM:
* Literally, take out text segments from USFM, translate them, and put them back into the original USFM structure, 1-for-1.
* Issues:
  * If the chapter already has text in it, what do you do?  The versifications are different!
  * If the source and target versification are different for that chapter, it creates problems such as being off by a verse
  * If the headers are different, it would overwrite what was in the target with the source
 
Option 2: use the target USFM:
* Using the existing target USFM structure, find where it matches the source and then stick it in (merged, missing, etc.)
* Keep the stuff in between the segments sent to machine.py
* Create USFM files per book (not by chapter)
* Give an option whether to include original target text or not
* Other considerations:
  * What if a segment name is for a larger (or smaller) span of verses - should that still be translated?
  * Should it alter the target USFM?  Should it combine or split verses?

Options:
* ~~Take section headers from a specific translation, different from the source? - not a priority~~
* ~~Use source header locations (overwrite target header locations)? - not a priority~~
* ~~Use source segmentation (verse ranges or subdivisions)? - not a priority~~
* Add 2 endpoints to download (1) each book and (2) the entire target with all Pretranslations, zipped
* If the target USFM book file is missing, use the source USFM structure

Program Flow:
* Take the pretranslations from the MongoDB
* Taking the target USFM from the Paratext zip file
* Stripping out the existing text (if chosen)
* Adding in the pretranslations to the target USFM in the mapped locations (using Versification)
* Return the whole USFM file to the user as a file

**Comment by ddaspit** [comment]
This is dependent on https://github.com/sillsdev/machine/issues/153.

**Comment by johnml1135** [comment]
Added rational from #264: 

> For teams that are using the AI-generated drafts as a quality checking tool, this download option would allow them to create the draft and save it, but without incorporating it into the project.
> For teams that are working in a secure setting, this download option would allow them to create the draft and share it with a teammate through an alternate channel with better security.
> For teams that want to compare the initial AI-generated draft to the first draft during team checking, this download option would allow the team to save the initial draft for later comparison.
