### ISSUE TITLE
SF: Editor: left/right alignment

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#250]
(I am assuming for Mother Tongue Drafting)

**Comment by Nateowami** [comment]
I don't know what this is supposed to mean, and Peter doesn't either. Are you talking about overwriting the project with the output of the engine (USFM and all)?

**Comment by mmartin9684-sil** [comment]
This is referring to the translation editing environment, with the reference translation on the left and the vernacular translation on the right, and is suggesting that we work to vertically align verses in the right hand panel with the same verses in the left hand panel.

**Comment by Nateowami** [comment]
We already do this. There will be some added effort in making the draft itself (before it is added to the project)

**Comment by pmachapman** [comment]
The reported issue is when there is a large amount of blank introductory material. This should be investigated to see if this use case works correctly.

**Comment by pmachapman** [comment]
See https://jira.sil.org/browse/SF-2620
