### ISSUE TITLE
SF: unsupported language code - better messaging

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#255]
This is a follow up to sillsdev/machine.py#62.  This is still and issue - because users can choose their training data and pretranslation data, they may inadvertently not choose any parallel training data and get this cryptic error.  We need (somewhere) to address this.  Is machine.py the best place?  Should SF tell the user that there is no parallel data in the selection of books for mother tongue drafting?

**Comment by pmachapman** [comment]
@johnml1135 Would it be possible to return a different HTTP code from Serval in these cases? Perhaps `422 Unprocessable Content`?

Or is there any other way we could detect that this is the specific use case in Scripture Forge?

**Comment by pmachapman** [comment]
See https://jira.sil.org/browse/SF-2619
