### ISSUE TITLE
Visibility into build and pretranslations

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#257]
As opposed to the high-touch SILNLP builds and pretranslations where all the data is available to the engineer, the SF builds are very opaque.  We need a method to determine all the factors of a build and fix/recreate/investigate it.

**Comment by johnml1135** [comment]
This includes #235 , #233 and https://github.com/sillsdev/machine.py/issues/53.

**Comment by BiancaPaw** [comment]
Per Tom/Michael: Would like to see a simple dashboard -- would like to review a mockup of how this would look

**Comment by johnml1135** [comment]
This also includes an addition to the Serval app (or onboarding app) to connect to Serval to investigate an existing build and debug, recreate, investigate the problem.  Specifically, that a non-engineer, system user can do this (don't need AWS credentials, but just a login).

**Comment by johnml1135** [comment]
This is addressed by the Serval Admin page in SF.
