### ISSUE TITLE
SF: Use AI drafts from multiple sources for quality checking

### ISSUE THREAD

**Issue by mmartin9684-sil** [sillsdev/serval#265]
For vernacular drafting, support the creation of multiple drafts from different source translations.

1. Same source language for each draft.
- Train an xx/yy translation model.
- Create multiple yy drafts of a book, using a different source translation (xx) for each draft.
For example, train an English/yy translation model, then create multiple drafts of GEN using the NIV, NLT, and NASB as source translations.
2. Different source languages for the different drafts.
- Train an xx/yy translation model, then translate book A from the source translation (xx) into the target language.
- Train a zz/yy translation model, then translate book A from the source translation (zz) into the target language.

This capability will be helpful to teams who are using the AI drafting feature as a quality checking tool.  It will also be useful for teams who are using the feature to prepare their first draft; for these teams.

User interface updates will be needed to present multiple drafts to the translator for review.

**Comment by johnml1135** [comment]
(1) is tracked here: https://github.com/sillsdev/serval/issues/267
(2) is being handled by https://github.com/sillsdev/silnlp/issues/295

**Comment by johnml1135** [comment]
There is a question about how best to present multiple drafts from multiple sources to the user that already has the chapter drafted.  There is a UI component (showing the two drafts side by side) and a SF/Serval data management component, associating multiple engines (or engines with multiple source corpora) with a single SF project.  This will need some design to determine the best solution.  See Micheal Martin for example users.

**Comment by pmachapman** [comment]
See https://jira.sil.org/browse/SF-2631
