### ISSUE TITLE
Mixed source configuration for AI drafting (vernacular)

### ISSUE THREAD

**Issue by mmartin9684-sil** [sillsdev/serval#266]
Frequently, a back translation is the best source text for fine-tuning a model that translates from the back translation language to the vernacular language.  In some cases, however, the back translation is too literal; although the training step produces very good metrics, the next-book drafting results are lower quality because the model has not trained with fluent text from the back translation language.

Pairing the back translation translation with a published Bible in the same language, and using the '`mapping: mixed_src`' setting on the corpus_pair, can produce better next book drafting results.

Sample config.yml corpus_pair setup:

`data:
  - corpus_pairs:
    src:
      - swh-sourceA
      - swh-sourceBT
    trg: wbi-targetC
    type: train,val
    mapping: mixed_src`

**Comment by johnml1135** [comment]
This is assumed to already be researched at a basic level and to produce "good enough" results.
As for mixing the source, half (configurable?) of the target is associated with one source (backtranslation), half with the other (published translation).  The verses are randomly split.

To implement, this would require:
* A means to assign 2 sources to a target and a % to assign to each
* The SF UI to enable this selection

1. Simple, clunky, manual implementation:
* SF allows for an arbitrary Paratext zip to be uploaded
* SILNLP can combine two sources into a split set of USFM files

2. SF only implementation
* SF allows a selection of 2 sources and a % of mixing each
* SF uses a machine library to combine the two sources
* SF pushes the combined source to Serval

3. SF + Serval implementation
* Same as 2, but Serval provides a utility in corpus definition for mixing sources (and targets?)

**Comment by johnml1135** [comment]
The Serval portion is done.  The SF is tracked outside of Github.
