### ISSUE TITLE
SF: Translation Drafting - use of project-specific Key Biblical Terms

### ISSUE THREAD

**Issue by mmartin9684-sil** [sillsdev/serval#270]
For translation drafting (back or vernacular), Scripture Forge currently uses the Key Biblical Terms (KBT's) lists from the source (reference) translation and from the project, and passes these pairings to Serval to help train the models.  However, most source (reference) translations are published Bibles, which are downloaded (via Paratext) from the Digital Bible Library (DBL).  These translations do *not* include the KBT's that were part of the original Paratext project.  The result is that, for most translation drafting projects, no KBT's are included in the training.

An alternative is to work with the KBT's in the project itself.

**Comment by pmachapman** [comment]
**Proposed technical solution**

*If:*
 - The target project has KBTs
 - The language of the source project matches one of the languages we have glosses for the KBTs
    * Usually this will be one of: `en, es, fr, id, pt-BR, pt-PT, zh-CN, zh-TW`
 - The source project does not have KBTs specified

*Then:*
 - Generate a list of KBTs for the source project with the glosses as definitions, and include in the data sent to Serval, corresponding to the KBTs in the target project.

***Note:** This change may prove redundant if SF/Serval's support for Paratext zip files is completed before this task is started.*

**Comment by pmachapman** [comment]
See https://jira.sil.org/browse/SF-2632
