### ISSUE TITLE
Rebuild bad SMT engine

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#271]
[error log.txt](https://github.com/sillsdev/serval/files/13932931/error.log.txt)

**Comment by johnml1135** [comment]
So, the trainsegmentpair is making an abort (at least not a crash!).  It is with engine 653aad26e73fc85d889be4e1.

![Screenshot 2024-01-16 5 35 59 PM](https://github.com/sillsdev/serval/assets/13733556/d0535b5f-3adb-411c-9cdc-e8ece4d3bc71)

**Comment by pmachapman** [comment]
@johnml1135 There is currently a build active for that translation engine, so we cannot start another?

```json
[
  {
    "id": "653aad30e73fc85d889be565",
    "url": "/api/v1/translation/engines/653aad26e73fc85d889be4e1/builds/653aad30e73fc85d889be565",
    "revision": 199,
    "engine": {
      "id": "653aad26e73fc85d889be4e1",
      "url": "/api/v1/translation/engines/653aad26e73fc85d889be4e1"
    },
    "step": 5632,
    "percentCompleted": 0.6757,
    "message": "Tuning translation model",
    "state": "Active",
    "options": {}
  }
]
```

**Comment by pmachapman** [comment]
@johnml1135 I noticed the job hadn't moved over the last hour, so attempted to cancel it via Swagger, but it wouldn't cancel. Any ideas?

**Comment by johnml1135** [comment]
@pmachapman - nothing - I tried the same thing and it is happening to me as well.  

Here is what I get for cancelling:
```
2024-01-16 20:52:22	
{"log":"\u001B[40m\u001B[32minfo\u001B[39m\u001B[22m\u001B[49m: System.Net.Http.HttpClient.SmtTransfer.ClientHandler[101]\n      Received HTTP response headers after 29.549ms - 200\n","stream":"stdout","time":"2024-01-17T01:52:21.638812944Z","type":"info","source":"System.Net.Http.HttpClient.SmtTransfer.ClientHandler"}
2024-01-16 20:52:22	
{"log":"\u001B[40m\u001B[32minfo\u001B[39m\u001B[22m\u001B[49m: System.Net.Http.HttpClient.SmtTransfer.ClientHandler[100]\n      Sending HTTP request POST http://machine-engine/serval.translation.v1.TranslationEngineApi/CancelBuild\n","stream":"stdout","time":"2024-01-17T01:52:21.609303347Z","type":"info","source":"System.Net.Http.HttpClient.SmtTransfer.ClientHandler"}
2024-01-16 20:52:22	
{"log":"\u001B[40m\u001B[32minfo\u001B[39m\u001B[22m\u001B[49m: System.Net.Http.HttpClient.SmtTransfer.LogicalHandler[100]\n      Start processing HTTP request POST http://machine-engine/serval.translation.v1.TranslationEngineApi/CancelBuild\n","stream":"stdout","time":"2024-01-17T01:52:21.609265246Z","type":"info","source":"System.Net.Http.HttpClient.SmtTransfer.LogicalHandler"}
```

If I restart the machine-server and machine-engine, it is still in the hung state.  It appears that if an engine is being built and then a docker container restarts, it gets stuck in a bad state.  @ddaspit - could that be possible?

**Comment by johnml1135** [comment]
Could it be that the readwrite lock has no timeout and that it gets created and never released?  Would that cause this behavior?  Shouldn't there be a small timeout, say, 10 seconds - at most 60 seconds?  How else would the active build that is clearly in the Mongo DB not be canceled?  @ddaspit do you have any thoughts?

**Comment by ddaspit** [comment]
When the job server restarts and a job is still running, Hangfire should restart the job. All distributed locks get released when the server restarts, so that probably isn't it. Maybe the job failed, but it wasn't able to update the Serval build status. It would be helpful to look at the Machine engine doc in Mongo.

**Comment by ddaspit** [comment]
I would guess that when Mongo when down, the job failed, but it wasn't able to update the build status, because, obviously, Mongo was down.

**Comment by ddaspit** [comment]
Are we running multiple instances of Mongo in a replica set? Mongo is a critical part of the infrastructure. We should probably consider moving to something like AWS DocumentDB, which has high availability guarantees.

**Comment by johnml1135** [comment]
We are not - only a single instance.  And moreover, the infrastructure is updated somewhat frequently which leads to downtimes of a few minutes every few weeks.  Also, we should likely look at [MongoDB Atlas](https://www.mongodb.com/cloud/atlas/lp/compare-mongodb-vs-documentdb?utm_source=google&utm_campaign=search_gs_pl_evergreen_atlas_competitor_prosp-nbnon_gic-null_amers-us_ps-all_desktop_eng_lead&utm_term=aws%20documentdb&utm_medium=cpc_paid_search&utm_ad=p&utm_ad_campaign_id=12314592717&adgroup=162875219948&cq_cmp=12314592717&gad_source=1&gclid=CjwKCAiAkp6tBhB5EiwANTCx1BlWenZ7fOAWgqHGSsYI-RoMUENoCAbN7ta0-NTZoNwsa8mg8BUFaBoCtwAQAvD_BwE) instead.

**Comment by johnml1135** [comment]
Either that, or we make our system able to handle long MongoDB outages (or both).

**Comment by johnml1135** [comment]
We will need to update:
* Serval builds: call it faulted
* Serval engines: Call it not active
* Machine engines: delete current build object

How should this be instagated?

**Comment by johnml1135** [comment]
@pmachapman, 653aad26e73fc85d889be4e1 has been manually cancelled and restarted.

**Comment by johnml1135** [comment]
https://github.com/sillsdev/machine/issues/158
