### ISSUE TITLE
Use MongoDB Atlas in production

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#273]
We should use it.  Let's hope it's under 1k/year.

**Comment by ddaspit** [comment]
We should investigate [AWS DocumentDB](https://aws.amazon.com/documentdb/) as well. It might be cheaper.

**Comment by johnml1135** [comment]
We may need to go with the dedicated server, that is, M10 for 0.08$ per hour ~= 700$/year.  M10 is the only one with a SLA which is 99.995%, or 131 seconds per month.

**Comment by ddaspit** [comment]
If we use MongoDB Atlas, we want to run it on [AWS](https://aws.amazon.com/solutions/partners/mongodb-atlas/).

**Comment by johnml1135** [comment]
Here is a migration plan:
* Put qa, int_qa and docker-compose on personal M0 Mongo Atlas (free teir) - use prefixes to enable the database names to not conflict.
* Put production on a M10 instance (normal naming)
* Migrate teh data with a series of backup and restore commands, [renaming the database](https://stackoverflow.com/questions/9201832/how-do-you-rename-a-mongodb-database) names as I go along (where needed).

**Comment by johnml1135** [comment]
We probably can go with Serverless: https://www.mongodb.com/community/forums/t/is-mongodb-serverless-suitable-for-production/184480

**Comment by johnml1135** [comment]
The mogodump is breaking from an esoteric error when it lasts too long.  The issue appears to be here: https://github.com/kubernetes/kubernetes/issues/74551
