### ISSUE TITLE
SF: Support for comparison drafting

### ISSUE THREAD

**Issue by mmartin9684-sil** [sillsdev/serval#278]
The initial release of Scripture Forge Translation Drafting is intended to create draft translations that the translators will review and edit on the way to preparing their first draft for that book.  However, a number of translation teams have identified an opportunity to use these drafts as a quality checking device.  That is, they would like to generate an AI draft for a book that the translator has already prepared, and then allow the translator to review this draft in comparison to their own draft.  Some teams have suggested creating several drafts (from different sources), so that the translator can compare their own draft to multiple AI drafts from different reference translations of the same book.

It should be possible to create these AI drafts as a batch (create drafts of book X from Source A and from Source B in a single request).

The translator will need to be able to work in Scripture Forge with these comparison drafts next to their own draft.  If the translator has created multiple comparison drafts, ideally it would be possible for the translator to work with each of the comparison drafts and their own draft concurrently.

Ideally, the translator would also be able to sync the comparison drafts (in some way) with Paratext, so that they could work with them in Paratext.

**Comment by pmachapman** [comment]
See https://jira.sil.org/browse/SF-2633
