### ISSUE TITLE
File and Corpora consistency

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#28]
I don't think this is the case, but files should not be allowed to be deleted that are in corpora.  The corpora should be deleted (or updated to remove the file) first.  To support this, files could have their own record of which corpora "contain" it - that is updated whenever corpora edits are made.
  As it is, corpora could be made inconsistent and cause builds to fail siliently.

**Comment by ddaspit** [comment]
Currently, when a file is deleted, it is automatically removed from all corpora.
