### ISSUE TITLE
SF/Serval: Option to translate and transfer inline elements from reference translation to target translation

### ISSUE THREAD

**Issue by mmartin9684-sil** [sillsdev/serval#297]
For Translation Drafting projects that are an adapting from a related language translation, transferring inline elements (such as footnotes and cross references) is actually a helpful practice.  Scripture Forge should offer a option to let the project administrator configure this option for their project.  Serval API's and backend functionality should support this capability when requested by the user.

**Comment by mmartin9684-sil** [comment]
Input from a translation coordinator using the AI drafting tech: previously there was an emphasis on translating for "clusters" of languages as a combined project.  But this is shifting into a "cascading" strategy where one translation project progresses ahead first and goes through the full translation "procedure", while the other translation projects follow behind and leverage the outcomes of the work on the first project.

For the projects that are "cascaded" behind the first project, it is helpful to have have inline elements such as footnotes and cross-references transferred from the first project to the cascaded project.  Ideally, text inside the inline elements, such as the footnote itself, would be translated into the target language.  Ideally, these transferred inline elements would be placed in the target language text in a similar place, rather than attached to the end of the translated verse text.

**Comment by johnml1135** [comment]
This has been implemented.
