### ISSUE TITLE
SF: Assign multiple sources for training

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#310]
This is only for training (not pretranslating). This is a spinoff from https://github.com/sillsdev/serval/issues/266 - we have found that mixing multiple sources really helps the bleu score.  This is for the SF implementation of it, both the selection of multiple sources (2 or more) and the creation of multiple corpora in Serval to enable this at the Serval level.  The Serval issue is tracked here: https://github.com/sillsdev/serval/issues/309.

**Comment by pmachapman** [comment]
See https://jira.sil.org/browse/SF-2615
