### ISSUE TITLE
SF/Serval: For multiple source training, allow users to specify training books by source text

### ISSUE THREAD

**Issue by bhartmoore** [sillsdev/serval#319]
Extends the random (or %-based random) source-mixing capability addressed in issues #266/309/310. 

This enhancement would allow for using a source with less coverage than the target, usually an incomplete back translation, by allowing the user to specify which books should be taken from which source. It does not require random source mixing within those books. Several teams using drafting cannot transition to drafting in SF without this feature. It is a need, but not an urgent one.

**Comment by johnml1135** [comment]
Would the logic be, always prefer one source to another if there is any text, or, prefer this source but only for the following books and chapters?

**Comment by bhartmoore** [comment]
Yes, conceptually very straightforward: use only source A for books in set [Y]; use only source B for books in set [Z]. I guess we may need some logic around the contingency of users selecting empty books.

**Comment by ddaspit** [comment]
This sounds like it should already be supported by Serval. SF will need to make changes to the UI and backend.

**Comment by johnml1135** [comment]
@bhartmoore - is this fully supported in SF to your needs?

**Comment by bhartmoore** [comment]
Just looked over the mixed source MVP with Peter. It's not yet possible to select books separately for each source. Two questions:

What will Serval will do when SF passes through two training sources? My assumption (and Peter's) is that it will mix them evenly where they both exist, and use the only source where only one exists, to cover the "training" books. 

I'd prefer to be able to select training books _per source_ - mix the books evenly if they are selected for both sources; otherwise use the only source with that book selected. Is this something current Serval supports if SF builds a separate book selection interface?

**Comment by johnml1135** [comment]
(gulp) it doesn't support this in a straightforward way, but it technically does.  You are correct in how Serval handles two sources, if there is only one it uses that, otherwise it mixes them.  The challenge is that there is only one book/chapter filter specified per corpus. To enable your desired use case this with the current implementation of Serval, SF, would have to do the following:
* Make 3 corpora one with both sources and the other two with only one of the two sources.
* For the books that are chosen for both sources, create a filter for the first, dual-source corpus choosing just those books.
* For the books that are chosen for just one source, create a filter for just that one corpus.

 So yes, it would support it, but not in an intuitive way.  It should be easy enough in SF to do it on a book level, but once we get to chapter level filtering, it would be quite challenging.  If we need that, we should likely add the Scripture filter to the individual files as well.

@pmachapman, do you have any insights?

**Comment by pmachapman** [comment]
> @pmachapman, do you have any insights?

Hmmm I see the difficulties. The most practical way does look like for SF to filter at a book level in the data we send through. Chapter level will be very difficult at the SF end.

What are the blockers at the Serval end to doing that level of filtering there?

In my naivete I would imagine an update to the `POST /translation/engines/build/{id}` endpoint that could look like:

```json
...
  "trainOn": [
    {
      "corpusId": "string",
      "textIds": [
        "string"
      ],
      "scriptureRange": "string",
      "files": [
        {
          "fileId": "string",
          "textIds": [
            "string"
          ],
          "scriptureRange": "string",
        }
      ]
    }
  ],
...
```

**Comment by johnml1135** [comment]
A few notes:
* Adding `textIds` to each file is a bit non-sensical, especially for text based files.  I would rather not do that.
* Adding `scriptureRange` to each textId is feasible (assuming that the two Scripture ranges would intersect).
* Adding the new field would make the interaction with Serval more intuitive

@pmachapman  and @ddaspit - do you have any objection to addressing this need by adding `scriptureRange` to each file in a corpus as well as the corpus all together?

**Comment by pmachapman** [comment]
> do you have any objection to addressing this need by adding scriptureRange to each file in a corpus as well as the corpus all together?

I am happy with just `scriptureRange`, as that is what we use for all builds now. We now only use text files for additional training files.

**Comment by johnml1135** [comment]
@pmachapman, looking at this again, it will be all sorts of weird in doubly defining both texts and scriptureRange in the one endpoint and how they work together.  The other contrast would be, again, to specify the same corpus 3 times, but with different Scripture ranges and TextId's.  @ddaspit  - do you have any insight which might be the best long term solution?

**Comment by johnml1135** [comment]
The best idea we have so far is the following:
* Add `sourceTextId` to the build json "trainOn" field.  This would filter down the corpus to only include one of the sources.
* All `trainOn` entries with the same `corpusId` are unioned together, such that if there are multiple sources in the same book for the corpus, they will be mixed.

**Comment by johnml1135** [comment]
What do we still need to determine before we can implement this?

**Comment by ddaspit** [comment]
We are waiting for SF to finish their design for this feature. We will be able to extract specific requirements from the design.

**Comment by pmachapman** [comment]
Here is the user workflow for Mixed Source:
![image](https://github.com/user-attachments/assets/3e7bca48-061b-426d-b066-5ef15b340ee6)

**Suggested Serval API Config Change**
```
"trainOn": [
  {
    "corpusId": "string",
    "sourceFileId": "string", // Optional
    "textIds": [
      "string"
    ],
    "scriptureRange": "string"
  }
],
```
**Notes**
- Group by corpusId
- If textids/scriptureRange is blank for one corpus/file, do not use that one for training
- If no sourceFileId specified use all files in corpus

**Comment by ddaspit** [comment]
I would like to verify a couple of things about the user workflow:

- Can the user select specific books for each target and source project?
- Can the user select which source project/books they want to draft from?
- When there are multiple target projects, are the subsequent projects treated as fallbacks? Will the user be able to order the projects by precedence?

It would probably be a good idea to meet to go over the workflow.

**Comment by bhartmoore** [comment]
Nathaniel, JoEllen and I met about this again today for clarifications. These are the outcomes so far--

- Yes, users can select separate books for each source and target project. The same book cannot be selected in more than one target project, but **can** be selected in multiple source projects for mixing.
- Yes, the user will select the source project and book(s) for the drafting step.
- There is no ordering of target projects. The user will select training data from the full set of books available in all targets, but the book options in different projects are mutually exclusive.

**Comment by ddaspit** [comment]
- Is the idea that the user will first select the target books and that will constrain the source books that are available to be selected, e.g. the user selects MAT, MRK, and LUK from the target projects, so the user will only be able to choose MAT, MRK, and LUK from the source projects?
- In theory, could the user choose to generate drafts from multiple source projects, e.g. use MAT from source project A and GEN from source project B?
- For each book, the user can only select one target project. Is that correct?

**Comment by bhartmoore** [comment]
- Yes, target book selection happens first and constrains the options for source book selection. 
- In theory, yes, and Joseph's original wireframes included this option. We all felt this should NOT be included in the first offering and it's not on the roadmap AFAIK. Teams can already do this (if needed) by initiating a new request.
- Correct; there is no mixing of target books. Once a book is selected for inclusion from one target project, the interface will disable selection of that book in all other target projects.

**Comment by ddaspit** [comment]
One last question, will the user choose which source project to generate translations from?

**Comment by bhartmoore** [comment]
Yes, the user will choose the source for translation in an early step when choosing which books to translate.

**Comment by ddaspit** [comment]
[Here](https://docs.google.com/document/d/1_EgVMqMaq_NtmjIo2phke49P38aR-YP-bfeo4U8VVcM/edit?usp=sharing) are some potential options for the API changes.

**Comment by pmachapman** [comment]
@ddaspit Just a small question: by corpus pair, do you mean that it will only contain two corpora, or that it can contain one or more?

If they can contain 1+ corpora (not just 1-2), should they be called a `corpora_set`?

Also, in regards to the proposals, I think either can be made to work with SF, given a `/v2/` API change for the options that break compatibility, and that existing data is migrated. If you do choose the breaking API route, I would estimate 2 months would be all that you would need the `v1` API to remain live until SF migrates over across all environments.

Option 2 probably looks the clearest to understand from my perspective.

**Comment by ddaspit** [comment]
Yes, a corpus pair would support multiple source and target corpora. I wanted a term that would convey that it is a parallel corpus (source and target) and not just a monolingual corpus. I could change the name to `parallel_corpora`.

**Comment by pmachapman** [comment]
Ah, I get what `pair` means now, in context. No need to rename.
