### ISSUE TITLE
Build Job Status error

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#32]
Make an NMT job, start it, cancel it, start it again.  It says that it is still canceled, even though it is running on ClearML.

**Comment by ddaspit** [comment]
Can you give more details on what exactly is happening? When a build is canceled, it calls the ClearML endpoint to stop the job. The job isn't necessarily stopped immediately. It could take a couple of seconds before the job actually stops depending on what command the job is currently executing. Does the ClearML job never stop?

**Comment by johnml1135** [comment]
Fixed - similar issues to SMT.
