### ISSUE TITLE
SF: Pretranslating for reviewing existing translations

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#320]
This would be used for creating a pretranslation as a review aid for an existing draft already in the target project.

Note, that for Serval, if there is any text in the target for the specific segment (verse), it will not create a pretranslation.  The target verses would need to be cleared out of the incoming texts before it got into Serval.

Would there be a checkbox to say "draft everything vs. draft only stuff that has not already been drafted"?

**Comment by pmachapman** [comment]
See https://jira.sil.org/browse/SF-2634
