### ISSUE TITLE
SF/Serval: when rebuilding with a new set of selected books, the old books are removed

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#321]
If I am correct Serval keeps the old translations.  Is SF removing them?  Is this the desired behavior?  Jeff Webster was surprised by this behavior - could we change it or document it better?

**Comment by johnml1135** [comment]
Serval deletes old pretranslations - should we do this?https://github.com/sillsdev/serval/blob/abf6f1399fab326b11ed606d8965e3e7151e1408/src/Serval.Translation/Services/TranslationPlatformServiceV1.cs#L91C1-L95C11

**Comment by ddaspit** [comment]
Is the issue that Serval removes all old pretranslations?

**Comment by Nateowami** [comment]
@johnml1135 This is the behavior I expect. Each request for a draft completely replaces previous draft requests. Users should import any chapters they want into the project before requesting another draft.

I think we are inadvertently encouraging users to use Serval inefficiently. I think users think if they select just one or two books the build will go quicker, and then they can come back later and have it draft another one or two. In reality, most of the build time is spent training the engine, not drafting. I think this user's confusion, and that of at least one other user I've interacted with, stems from this misunderstanding. If we can clearly communicate to the user that they should not use the tool this way, I don't think they'll end up in the situation where they've requested a draft for one book, and shortly afterwards have requested a draft of another book, without first importing the prior book to the project.

**Comment by johnml1135** [comment]
One feature we could potentially prioritize is to inference a few more
books from the last build. This would give a drafting time of 10 to 20
minutes rather than 8 hours.  I think it would have the most value if
people change their decision as to what books they want to work on. How
often does that happen?

**Comment by johnml1135** [comment]
Is there anything we can do to communicate to the user's better the
existing functionality as we determine how to prioritize quick inferencing
from previous builds?

**Comment by johnml1135** [comment]
Let's at least update the documentation in Serval to reflect what it does.  @Nateowami  - should SF update the documentation as well?
