### ISSUE TITLE
Webhook Produces Invalid JSON

### ISSUE THREAD

**Issue by pmachapman** [sillsdev/serval#328]
I am trying to use the webhooks to update Scripture Forge when a build completes, but am unable to parse the JSON sent by the webhook due to the JSON being invalid.

Sample data I have received includes:
```json
{"event":"TranslationBuildStarted",{"build":{"id":"65d65811352b5d93e8a2c02d","url":"/api/v1/translation/engines/65c94648352b5d93e8a24538/builds/65d65811352b5d93e8a2c02d"},"engine":{"id":"65c94648352b5d93e8a24538","url":"/api/v1/translation/engines/65c94648352b5d93e8a24538"}}}
```
```json
{"event":"TranslationBuildFinished",{"build":{"id":"65d65811352b5d93e8a2c02d","url":"/api/v1/translation/engines/65c94648352b5d93e8a24538/builds/65d65811352b5d93e8a2c02d"},"engine":{"id":"65c94648352b5d93e8a24538","url":"/api/v1/translation/engines/65c94648352b5d93e8a24538"},"buildState":"Completed","dateFinished":"2024-02-21T20:09:34.131Z"}}
```
With JSON.NET returning the error:
```
Newtonsoft.Json.JsonReaderException : Invalid property identifier character: {. Path 'event', line 1, position 35.
```
An online JSON parse I used returned this error (I used this to ensure it was not a Json.NET bug):
```
Expected double-quoted property name in JSON at position 36 (line 1 column 37)
```

Also, modifying the Serval Webhook unit test to display the JSON generated returns invalid JSON too:
```json
{"event":"TranslationBuildStarted",{"buildId":"build1","engineId":"engine1"}}
```

So I don't believe it is an error at the client end. I couldn't find any tests that parse the JSON, so I there might be some configuration I missed for parsing the JSON?

**Comment by johnml1135** [comment]
@ddaspit  - why did you put in `[JsonExtensionData]` under `WebhookPayload`'s `Payload`? That makes the Json invalid.  Was that intentional?

**Comment by ddaspit** [comment]
To tell you the truth, I don't remember why. Maybe it used to work differently and I forgot to remove the attribute.
