### ISSUE TITLE
Translation TextID and Refs should include text line

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#33]
Otherwise, how are they mapped?  It would be a mess...  If no reference, make the reference the line number?

**Comment by ddaspit** [comment]
I assume you are talking about pretranslations. All pretranslations have a reference. If the reference isn't specified in the text file, then the line number is used. The ref format is `<text_id>:<line_number>`. If it is Scripture, then the verse ref is used.

**Comment by ddaspit** [comment]
Machine was not properly setting the ref when calling the `InsertPretranslations` endpoint of the `TranslationPlatformApi` gRPC service. This has been fixed in Machine.

**Comment by johnml1135** [comment]
FYI, commit [acb923df](https://github.com/sillsdev/machine/commit/acb923df156fac12441d4331da7b063e4acc4a4f) solved the issue
