### ISSUE TITLE
Missing required properties in ClearML Metrics Event

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#332]
System.Text.Json.JsonException: JSON deserialization for type 'SIL.Machine.AspNetCore.Models.ClearMLMetricsEvent' was missing required properties, including the following: min_value_iteration, max_value_iteration

**Comment by johnml1135** [comment]
@ddaspit  and @Enkidu93  - its it ok if I change ClearMLMetricsEvent so that MinValueIteration and MaxValueIteration are not required?  Should it be purely optional?

**Comment by Enkidu93** [comment]
Yeah, judging from the Clearml API docs, all of the fields in the last metrics event are optional (although it seems odd to me that the metric name and variant would be). See [here](https://clear.ml/docs/latest/docs/references/api/definitions#tasks-last_metrics_event). Damien is the one who most recently altered code that has to do with that functionality, so he might have a reason.
