### ISSUE TITLE
Serval and Machine memory leak

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#338]
You tell me what's happening:
![image](https://github.com/sillsdev/serval/assets/13733556/a5ad9d6a-d9d4-48af-b1c7-4709147d1689)

**Comment by johnml1135** [comment]
@ddaspit - do you know what could be happening?  It appears that all the files are opened within a "using" block and that mongo connections are properly disposed.  Do you have any guesses before I start dumping memory and looking around?

**Comment by johnml1135** [comment]
dotnet-counters
```
Name                                                               Current Value
[System.Runtime]                                                                
    % Time in GC since last GC (%)                                         0    
    Allocation Rate (B / 1 sec)                                      196,648    
    CPU Usage (%)                                                          0.378
    Exception Count (Count / 1 sec)                                        0    
    GC Committed Bytes (MB)                                               99.877
    GC Fragmentation (%)                                                  19.795
    GC Heap Size (MB)                                                     39.445
    Gen 0 GC Budget (MB)                                                  16    
    Gen 0 GC Count (Count / 1 sec)                                         0    
    Gen 0 Size (B)                                                 4,665,968    
    Gen 1 GC Count (Count / 1 sec)                                         0    
    Gen 1 Size (B)                                                    64,104    
    Gen 2 GC Count (Count / 1 sec)                                         0    
    Gen 2 Size (B)                                                45,137,560    
    IL Bytes Jitted (B)                                           27,882,817    
    LOH Size (B)                                                   1,569,592    
    Monitor Lock Contention Count (Count / 1 sec)                          0    
    Number of Active Timers                                                6    
    Number of Assemblies Loaded                                          208    
    Number of Methods Jitted                                         412,686    
    POH (Pinned Object Heap) Size (B)                              2,112,192    
    ThreadPool Completed Work Item Count (Count / 1 sec)                  11    
    ThreadPool Queue Length                                                0    
    ThreadPool Thread Count                                                4    
    Time paused by GC (ms / 1 sec)                                         0    
    Time spent in JIT (ms / 1 sec)                                         0    
    Working Set (MB)                                                     353.059
```

**Comment by ddaspit** [comment]
I'm not sure I understand what the issue is.

**Comment by johnml1135** [comment]
The memory footprint keeps expanding over time until it hits the memory limit of the container.

**Comment by johnml1135** [comment]
machine-engine ran out of Memory at 2.5GB and serval-api is at 90% of 350MB.
Maybe we should set `DOTNET_GCHeapHardLimitPercent` as per https://learn.microsoft.com/en-us/dotnet/core/runtime-config/garbage-collector...

**Comment by ddaspit** [comment]
I wouldn't worry about serval-api right now. ASP.NET Core will reserve memory to optimize performance. The memory usage for serval-api is pretty flat. If we aren't getting out of memory issues, then we should be okay. machine-engine needs a decent amount of memory for SMT engines. We might need to increase the memory for the machine-engine container.

**Comment by johnml1135** [comment]
Ok - do you have an idea for the RAM needed?  4GB?  8GB?

**Comment by ddaspit** [comment]
Depending on the size of the SMT model, it can be anywhere from a couple of 100MBs to a couple of 1GBs. It depends on how many models we want to be able to load in memory at a time. I would suggest allocating more than 8GB. In the range of 32-64GB would be better.

**Comment by johnml1135** [comment]
So, 2 issues I can see - one is that there is only ~2GB of RAM for Machine Engine (and RAM is somewhat expensive for prod), the other is the question how machine-engine determines how many models to load simultaneously, or machine-job does for how many jobs to run simultaneously.

**Comment by johnml1135** [comment]
It is filling the available space - I just increased the RAM and all the engines are just gobbling up more!  We will need to address this other than just adding more RAM.

![Image](https://github.com/sillsdev/serval/assets/13733556/31c6c2c3-065f-4c07-a1c9-ae10c8057b38)

**Comment by johnml1135** [comment]
We don't know enough - we can start by using [speedscope](https://github.com/jlfwong/speedscope) to [analyze dotnet logs](https://github.com/jlfwong/speedscope/wiki/Importing-from-.NET-Core) from docker-compose while running E2E tests.  That should give us some understanding of onloading and offloading models.

**Comment by johnml1135** [comment]
dotnet counters on production machine-engine:
```
Name                                                               Current Value
[System.Runtime]                                                                
    % Time in GC since last GC (%)                                         0    
    Allocation Rate (B / 1 sec)                                    1,027,064    
    CPU Usage (%)                                                          1.989
    Exception Count (Count / 1 sec)                                        0    
    GC Committed Bytes (MB)                                              141.791
    GC Fragmentation (%)                                                  22.604
    GC Heap Size (MB)                                                    104.562
    Gen 0 GC Budget (MB)                                                 335    
    Gen 0 GC Count (Count / 1 sec)                                         0    
    Gen 0 Size (B)                                                92,957,952    
    Gen 1 GC Count (Count / 1 sec)                                         0    
    Gen 1 Size (B)                                                 1,893,680    
    Gen 2 GC Count (Count / 1 sec)                                         0    
    Gen 2 Size (B)                                                 9,654,760    
    IL Bytes Jitted (B)                                            7,848,139    
    LOH Size (B)                                                  25,507,336    
    Monitor Lock Contention Count (Count / 1 sec)                          1    
    Number of Active Timers                                               14    
    Number of Assemblies Loaded                                          180    
    Number of Methods Jitted                                         196,041    
    POH (Pinned Object Heap) Size (B)                                274,880    
    ThreadPool Completed Work Item Count (Count / 1 sec)                  84    
    ThreadPool Queue Length                                                0    
    ThreadPool Thread Count                                                4    
    Time paused by GC (ms / 1 sec)                                         0    
    Time spent in JIT (ms / 1 sec)                                         0    Complete
    Working Set (MB)                                                   2,667.418
```
Note that there is 2.667 GB of working Set memory - which is more than everything else combined.  I did a quick test on docker-compose and found that after spinning up machine-engine and running a few E2E tests, I had around 260 MB of RAM (and never when down, even after the engines were unloaded). Yet, if I had a recurring task to call GC.Collect(), then the memory was reduced to around 127MB.  It also appears that based upon our service (processing different batches of data), that explicitly calling GC.Collect() [could be appropriate](https://stackoverflow.com/questions/478167/when-is-it-acceptable-to-call-gc-collect).

### Proposal
* Move RecurringTask from Machine to Serval.Shared/Services
* Add new class for Collecting Garbage every x minutes (configurable during dependency injection) to Serval.Shared/Services
* Use the [double Collect call](https://learn.microsoft.com/en-us/answers/questions/350963/why-gc-collect()-call-twice-required-when-use-gc-w).
* Have all 4 services (including echo) use the recurring garbage collection (taking the performance hit for long-term stability).

@ddaspit - what do you think?

**Comment by johnml1135** [comment]
Update, I think explicitly calling the garbage collector is probably not needed. There are different settings that can be applied to the garbage collector. I will research these and figure out which ones are best and we'll optimally address our issue. https://learn.microsoft.com/en-us/dotnet/core/runtime-config/garbage-collector

**Comment by johnml1135** [comment]
Ok, I think I figured it out: https://learn.microsoft.com/en-us/dotnet/core/runtime-config/garbage-collector#retain-vm
* The default Garbage Collector memory threshold is 90% - which is what we see machine-engine controlling to in the image at the top
* There are two main ways to doing garbage collection, workstation and server - we should use server.
* We need to optimize:
  * The amount of memory for each process
  * The garbage collection threshold (it will let sleeping dogs lie unless it passes the threshold) should be set so that we balance performance (set it higher), allow threshold between it and the warning limit (set it lower) and get visibility into whether it is likely to cause things to crash (set it lower).

### Proposal
* Set GC settings to server for all
* Set GC threshold to 85% and warning level to 95% - that should tell us that we actually need more RAM for the process and that GC is failing.
* If we need more RAM, we can scavenge from other containers (potential) , we can add more RAM or we can do things to reduce RAM usage, such as rework the machine-engine unloading algorithm to not use 10 minutes but respond to available memory (or similar).

**Comment by ddaspit** [comment]
I believe that the main issue with out of memory exceptions is because of the SMT models. The SMT models are loaded in native code, which is not controlled by the .NET GC. Currently, there is no limit on the number of SMT models that can be loaded at a time. After a period of inactivity, the models are unloaded. We need to update the SMT engine to limit the number of models that can be loaded at the same time. That will allow us to limit the memory usage to a level that our hardware supports.

**Comment by johnml1135** [comment]
Below are two graphs of RAM usage over the past 2 weeks, the first as a % of the limit, the second as absolute GB.  On April 10th, more RAM was added to the servers - as you can see, RAM usage increased across the board to fill the available space.  There was no increase of load, but just that the GC responded differently when there was more memory available.  This leads me to believe that by making changes to the GC, at least by bringing the "upper threshold" to 80% and the alert limits to 95% would be more sensible for our application.  Other settings changes beyond that may or may not be helpful.

![image](https://github.com/sillsdev/serval/assets/13733556/91de86ac-43ff-4436-b6de-6d24ab362a19)

![image](https://github.com/sillsdev/serval/assets/13733556/2d6d278b-f3c1-441c-be49-3cc2d0cbcea5)

**Comment by johnml1135** [comment]
Here is the RAM as of this morning:
![image](https://github.com/sillsdev/serval/assets/13733556/df3f03e6-d744-4719-99e9-c077ca10f2fe)

Machine-engine keeps rising (not being garbage collected) and machine-job crashed and restarted.  One more check (try workstation server settings) but otherwise, I think we can say that there is a memory leak.

**Comment by johnml1135** [comment]
dotnet-counters:
```
Press p to pause, r to resume, q to quit.
    Status: Running

Name                                                               Current Value
[System.Runtime]                                                                
    % Time in GC since last GC (%)                                         0    
    Allocation Rate (B / 1 sec)                                      174,392    
    CPU Usage (%)                                                          0.218
    Exception Count (Count / 1 sec)                                        0    
    GC Committed Bytes (MB)                                               84.66 
    GC Fragmentation (%)                                                  56.163
    GC Heap Size (MB)                                                     43.747
    Gen 0 GC Budget (MB)                                                 335    
    Gen 0 GC Count (Count / 1 sec)                                         0    
    Gen 0 Size (B)                                                26,693,312    
    Gen 1 GC Count (Count / 1 sec)                                         0    
    Gen 1 Size (B)                                                   612,224    
    Gen 2 GC Count (Count / 1 sec)                                         0    
    Gen 2 Size (B)                                                 8,761,496    
    IL Bytes Jitted (B)                                            4,853,481    
    LOH Size (B)                                                  44,289,392    
    Monitor Lock Contention Count (Count / 1 sec)                          0    
    Number of Active Timers                                               15    
    Number of Assemblies Loaded                                          180    
    Number of Methods Jitted                                          84,098    
    POH (Pinned Object Heap) Size (B)                                398,480    
    ThreadPool Completed Work Item Count (Count / 1 sec)                   6    
    ThreadPool Queue Length                                                0    
    ThreadPool Thread Count                                                5    
    Time paused by GC (ms / 1 sec)                                         0    
    Time spent in JIT (ms / 1 sec)                                         0    
    Working Set (MB)                                                   3,500.036
```

**Comment by johnml1135** [comment]
From Damien: It likely just needs more RAM.  Let's do these now:
* Increase RAM
* Gracefully recover: https://github.com/sillsdev/machine/issues/158

Longer term we may:
* Split NMT and SMT engines
* Run SMT jobs on ClearML
* investigate leaks?
* Limit the number of simultaneous SMT engines - https://github.com/sillsdev/serval/issues/362

**Comment by ddaspit** [comment]
Here is a simple way to investigate for memory leaks with the SMT models:

- Run an instance of Serval/Machine on a local dev machine
- Initiate a couple of SMT build jobs
- Monitor memory usage to see if continues to increase without stabilizing
- We could turn on the workstation GC and insert `GC.Collect` calls after a job to remove the variable of the .NET GC holding on to managed memory

**Comment by johnml1135** [comment]
Machine-engine: 2.7 GB
Machine-job: 8.5 GB

![image](https://github.com/sillsdev/serval/assets/13733556/6cafc995-7d43-4e59-aab3-ae87197ab217)

I am putting local docker through the ringer.  I am running full Bible SMT jobs back to back, where I run the SMT job and then translate one segment from the completed engine.  The numbers above are from working on the 9th job.  After the first job, the numbers were about 3.5 GB for machine-job and 500 MB for machine-engine.  Some things appear to be being unloaded, but there is a severe memory leak.

Possible solutions:
* Keep running and see if it actually stabilizes.
* Fix the memory leak - that may be harder to do ... or not.  This could be chasing a long tail.  It would be better to fix this by definition instead.
* Manually load/unload dlls.  This is not possible with NetStandard - would need .Net and [NativeLibrary](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.nativelibrary?view=net-5.0)
* Spin off separate processes to deal with the DLL's

Spinning off engines may be best.

**Comment by johnml1135** [comment]
3.3 GB and 9.1 GB at 11 jobs...

**Comment by johnml1135** [comment]
Proposal:
* For SMT jobs, make a new process in SMTTransferBuildJob when doing work.  Pass it parameters through the command line.  The job can be cancelled (terminated) or it will terminate when complete.
* For SMT live inferencing, load a new process per model loaded.  They are communicated over using a named pipe [with method calls](https://github.com/RandomEngy/PipeMethodCalls) and the processes will be killed after not being used for 10 minutes (or whatever other algorithm is needed).

**Comment by johnml1135** [comment]
3.4 GB and 10 GB for 15 jobs.  I'll let it run overnight.

**Comment by johnml1135** [comment]
4.0GB and 11.5 GB and 20 runs.

**Comment by ddaspit** [comment]
I think it would be helpful to turn on the workstation GC for these tests. The workstation GC is very aggressive in reclaiming memory. It would remove the variable of the server GC keeping memory around for optimization purposes.

**Comment by johnml1135** [comment]
Workstation GC was turned on for these tests.  I turned it on to handle that exact purpose - I started to think it was not the GC at all and I wanted to remove it from the conversation.

**Comment by johnml1135** [comment]
@ddaspit  - what do you think about my proposals?  Don't worry about fragmentation of C++ code, but just eliminate all memory leaks by design?  It shouldn't be that bad and the overhead would be minimal.  It would prevent us from needing ever expanding RAM requirements and from getting rid of any leak anywhere.  Probably it's not been as much of an issue because locally, people are only running one model and for SF, they haven't had as many people using it.

**Comment by ddaspit** [comment]
If there are memory leaks, I would like to focus on trying to fix those first.

**Comment by johnml1135** [comment]
One further point, it would be straightforward for me to implement the fix of making a new process, but it would likely take you substantial time to actually fix the memory leaks, unless I started to get familiar with the thot library.

**Comment by johnml1135** [comment]
Plan:
* Move SMT jobs to ClearML (use a env variable flag to switch between them)
* Move more RAM to machine-engine server from machine-job
* Damien will (long term) test the RAM for local loading - spin off to #380.

**Comment by johnml1135** [comment]
This is spun off to new issues.  This issue can now be closed.
