### ISSUE TITLE
delete engine - and then all files

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#342]
Often the files are only associated with one engine.  A client may want to auto-delete all files associated with an engine with one command.

**Comment by ddaspit** [comment]
We could add an optional parameter to the delete endpoint for engines/corpora to also delete all associated files.

**Comment by Enkidu93** [comment]
@pmachapman Is this something that SF still needs/would like?

**Comment by pmachapman** [comment]
> Is this something that SF still needs/would like?

@Enkidu93 Yes, it will mean we can simplify and speed up the time taken to delete a project. It will primarily help with automated testing. It is not a high priority, though.

**Comment by Enkidu93** [comment]
> > Are there ever situations in which multiple engines are sharing the same files?
> 
> @Enkidu93 Not for any of Scripture Forge's translation engines.

OK, excellent. Thank you!
