### ISSUE TITLE
Ability to change the source/target language for a translation engine

### ISSUE THREAD

**Issue by pmachapman** [sillsdev/serval#35]
The language for a Paratext project can be changed in the registry, so we are currently adding support to Scripture Forge to allow this to be handled properly there (see SF-2083).

Would it be possible to have a PATCH endpoint for the translation engine so that we can update the source/target language when it has changed in PT/SF?

**Comment by johnml1135** [comment]
@pmachapman, The engines are trained with specific language pairs.  The language id's are deeply embedded in how it is encoded.  For instance, if the language changed and you translate, how should that work?  With the old or new language code?
  There are enough complications with how this would work that it would be best to delete the engine and then create it from scratch.  SF may need to do this other times if for instance the data becomes corrupted or lost (not likely but a possibility.
  I would recommend the following plan:
* If the language changes, keep using the existing models, pretending that the language has not changed.
* At the same time, make a new engine and rebuild everything
* After everything is rebuilt, change over to using the new engine and delete the old one
  @ddaspit, do you have any other thoughts?

**Comment by pmachapman** [comment]
That sounds logical. Thank you for looking into this and your recommendations, @johnml1135 - I will create a JIRA ticket for SF, to look into this as it seems like an SF problem, not a Serval problem.

**Comment by ddaspit** [comment]
Recreating the engine makes sense to me.

**Comment by johnml1135** [comment]
I am closing this as there is a low cost resolution - recreate the engine.
