### ISSUE TITLE
Use ClearML service accounts

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#351]
We have 2 accounts from ClearML that have just become available.  We can use one for all of our deployment environments and one for the onboarding app.  That should eliminate the need for onboarding users to need their own ClearML creds and hopefully tap down on ever expanding user needs (if they are not going to be interacting with the ClearML GUI directly).

**Comment by johnml1135** [comment]
One service account for production that just has access to `production/` projects and queue, another account for QA and onboarding app, that does not have access to production queue and projects.

**Comment by Enkidu93** [comment]
The service account is being used in the Onboarding Dashboard. @johnml1135 , are these up in Serval yet?

**Comment by johnml1135** [comment]
No, they are not - I just asked ClearML if we could get a few more accounts.  It would be nice to have at least one for QA and one for production.

**Comment by johnml1135** [comment]
We will be getting 2 more service accounts (to total 4) in a day or two.  We could split them up this way:
1. Onboarding/automated SILNLP jobs
2. Production serval
3. QA Serval
4. dev/docker compose/github actions Serval

What do you think?

**Comment by Enkidu93** [comment]
> We will be getting 2 more service accounts (to total 4) in a day or two. We could split them up this way:
> 
>     1. [silnlp] Onboarding/automated SILNLP jobs
> 
>     2. [production.serval] Production serval
> 
>     3. [qa.serval] QA Serval
> 
>     4. [dev.serval] dev/docker compose/github actions Serval
> 
> 
> What do you think?

That seems reasonable to me!

**Comment by Enkidu93** [comment]
Is this complete, @johnml1135?

**Comment by johnml1135** [comment]
I still need to convert over production and QA.  I was waiting for the S3 bucket dust to settle first.

**Comment by johnml1135** [comment]
Prod and QA are converted.
