### ISSUE TITLE
RWLock creation issue

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#36]
RWLock's are created in the MongoDB when they are needed.  This creates an issue in that "create when needed" and "check if the lock is available" are merged into one check, specifically `FindOneAndUpdateAsync` with `upsert` filtered on both the engineID and the logic to see if the lock is available.   When the new ID is created (if one does not exist), it will then create a duplicate engineID entry.  Also, mongoDB $expressions are not allowed with upsert.
  This issue was exposed when trying to cancel a build that is in process - and/or an instance when the locking mechanism is actually used.
  The proposal is to:
* Create the mongoDB RWLock instance when creating the Lock in dotnet (if not already created)
* Remove the "upsert" capability when trying to acquire the lock - it already exists because we just created it.
* If there is a duplicate entry, actually fail, don't just "not acquire the lock" - there should be no duplicates.

**Comment by ddaspit** [comment]
This approach sounds reasonable to me.

**Comment by johnml1135** [comment]
Also, always generate the new ID in the data file or engine controller - and then pass it to the database.  The data structures need a valid ID to be passed around.
