### ISSUE TITLE
Error when specifying Psalm 151 in scriptureRange

### ISSUE THREAD

**Issue by pmachapman** [sillsdev/serval#365]
If I attempt to start a build with a scriptureRange that contains Psalm 151, for example "PHM;3JN;PS2", I receive the following error from StartBuildAsync:

Status: 400
Response: "The scripture range PHM;3JN;PS2 is not valid: PS2 is an invalid chapter number."

Note: The only other book I could find that ends in a number is PS3: Psalms 152-155 (these are in Syraic)

**Comment by Enkidu93** [comment]
Thank you so much! Good catch. I'll go ahead and fix this.
