### ISSUE TITLE
Clean up engines/builds that were created incompletely

### ISSUE THREAD

**Issue by ddaspit** [sillsdev/serval#374]
It is possible for engines/builds to be in a state where the model exists in the Serval database, but the engine/build was not successfully created by the engine service.  I'm not sure how frequently this occurs. I believe that it is fairly unlikely, but still possible. 

One possible way to deal with this case is to add a flag to the engine/build model that indicates if the engine/build was successfully created by the engine service. When the engine/build is initially created the flag will be set to `false`. Once the engine/build is created by the engine service, the flag is set to `true`. A worker service could periodically check for engines/builds that have not been successfully created after a specified timeout (could be short) and clean up the engine/build.

**Comment by johnml1135** [comment]
The incomplete engines should all be resolved enough by 1.5.  This is to delete the old data from the hard drive.

**Comment by johnml1135** [comment]
I don't see this as a major concern at this point.  There are at max only a few Gigs of space that are being used and no more that would be projected.  The time is likely not worth the savings at this point.

**Comment by ddaspit** [comment]
We still haven't implemented proper support for this, so I would like to keep this open. It is still possible for an engine to get out of sync between Serval and the engine service.
