### ISSUE TITLE
Error: The USFM does not contain an 'id' marker.

### ISSUE THREAD

**Issue by pmachapman** [sillsdev/serval#375]
Sometimes projects will contain extra USFM files that do not contain an `\id` marker. Once such case happened in the most recent workshop in Korea. (There is a thread in the Scripture Forge Slack about this - search for "The USFM does not contain an 'id' marker.")

Paratext will currently insert an `\id` tag when you save a file in this state, but it seems older versions of Paratext did not do this.

The error as it stands is not terribly helpful - it doesn't say which file has the problem, so when we report it, it is difficult for the user to resolve.

Could we either display the affected book name, or perhaps just grab the Id from the filename (this method would be preferred by me)? Stripping out the `<FileNamePrePart>` and `<FileNamePostPart>` values defined in the Project Settings XML (if they are present) would make this possible, and then removing the digits from the filename would generate the ID.

**Comment by marksvc** [comment]
After the user got `\id` added to the missing book (or maybe deleted the book?), and all books in the project seemed to have an `\id` tag, the user seemed to continue to receive an error about a missing `\id` marker. So maybe there is more to this, or maybe the system was not bundling up the USFM we thought it was.

**Comment by bhartmoore** [comment]
LhrNBT is also receiving this error when requesting a back translation draft. I checked each file for \id lines (as did the user) and found 3 that looked suspicious (e.g. extraneous characters from another script), but none that broke the format "\id LUK some text here." The user retyped the 3 suspicious id lines by hand and now the back translation build appears to be working normally; still waiting on confirmation. We need some clarity on what is triggering this `System.InvalidOperationException: The USFM does not contain an 'id' marker` error. User adds: "For Lhr and LhrNbt I ran the Basic Marker Checks and Schema marker checks for GEN and the NT books. I found two potential issues and fixed them but neither resolved the generation failure."

![Screenshot 2024-04-20 064343](https://github.com/sillsdev/serval/assets/127882639/76c4541b-76d5-4eb7-b89a-4e539fb96470)

**Comment by ddaspit** [comment]
I tried out the LhrNBT and Lhr projects from the S3 bucket and did not receive an error. Maybe it has something to do with the way that SF is bundling the project. I would appreciate it if someone could send me a project zip that is exhibiting this issue.

**Comment by Nateowami** [comment]
@ddaspit It could have been in a source project. If we logged the file name the error occurs in, it would be easier to track down which project has the problem.

**Comment by bhartmoore** [comment]
Next time we get a report of this issue I'll try to get a zip of the relevant projects before we attempt to resolve it.

**Comment by johnml1135** [comment]
I have a fix for the issue that tests out.  I am assuming that an acceptable ID would be, for a book titles `01GENBIBL.SFM`; `GEN - BIBL`.  This would be used if there is no `\id` in the entry.

**Comment by pmachapman** [comment]
> I am assuming that an acceptable ID would be, for a book titles 01GENBIBL.SFM; GEN - BIBL.

Would this work correctly if we uploaded two sources? (i.e. is the ID used for matching the two books if they present in the two sources)

My understanding of the logic in `UsfmZipText.GetId()`, is that if it was fed `\id GEN - BIBL`, it would extract `GEN`?

**Comment by ddaspit** [comment]
@pmachapman  Yes, you are correct, it wouldn't work. @johnml1135 has reverted that fix.

**Comment by pmachapman** [comment]
@ddaspit The translation engine id is 6626b9b28d3131ee8e620436. The problem file is 94XXAPT1868.SFM in corpus id 6625d2ccd636353d0686b855.

I have attached the zip files from Serval (these are just my test projects).
 * Source: [6625d2ccd636353d0686b855.zip](https://github.com/sillsdev/serval/files/15067780/6625d2ccd636353d0686b855.zip)
 * Target: [6625d2ccd636353d0686b855.zip](https://github.com/sillsdev/serval/files/15067782/6625d2ccd636353d0686b855.zip)

**Comment by ddaspit** [comment]
@pmachapman  That is perfect. Thank you.
