### ISSUE TITLE
Get Peter creds

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#378]
S3 bucket min access creds for docker-compose
ClearML service agent creds

**Comment by Enkidu93** [comment]
Our conclusion regarding service accounts given we only are able to have two (?) is that we'd have one service account for production serval jobs and another for QA serval as well as onboarding. Is that correct, @ddaspit? I'm happy to go ahead and make this happen. I also know @mshannon-sil was offering to set up service accounts.

**Comment by ddaspit** [comment]
@Enkidu93  Yes, that is what we want.

**Comment by Enkidu93** [comment]
I'm seeing two service accounts already there - `serval` and `silnlp`. Did you @johnml1135 or @mshannon-sil  create these for production and QA/onboarding? If so, should we rename them to make their intended scopes clear?

**Comment by mshannon-sil** [comment]
I think John set those up, but it looks like they've never been used, so we can go ahead and rename them. If you need administrator access to rename them/get credentials, I can take care of that.

**Comment by Enkidu93** [comment]
OK, sounds good! I have admin access, so I should be good to go - thank you!

**Comment by Enkidu93** [comment]
Ideas for naming? I'll do `serval-production` for the one, but what about the other since its intended use is twofold? `testing`? `research`? `serval-testing-and-onboarding`? `internal`?

**Comment by mshannon-sil** [comment]
I'm in favor of `serval-testing-and-onboarding` since it's most specific/accurate, and none of the general names quite capture the purpose.

**Comment by Enkidu93** [comment]
Partial duplicate of #351

**Comment by johnml1135** [comment]
Should be complete now.
