### ISSUE TITLE
SMT builds on ClearML

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#382]
A spin off of https://github.com/sillsdev/serval/issues/338.  We need to:
* Move SMT jobs to ClearML (use a env variable flag to switch between them)
* Move more RAM to machine-engine server from machine-job

Proposal Workflow:
  * Prep all the data to build the SMT engine
  * Place the data on the S3 bucket under `builds/{buildId}` folder
    * Note: Use the standard `builds` and `models` folders in the S3 bucket, as well as the model naming convention
  * Place the job on the ClearML CPU only queue using a new env variable `ClearML__Cpu_Queue`
  * The ClearML job (machine.py) does the following:
    * Copy the S3 bucket data locally to `/tmp` or similar
    * Run the job as per the instructions (either given in the command line or a configuration file)
    * Update the status through ClearML values
    * Zip the model folder and place it in `models/<standard naming>` 
  * Pre and Post SMT jobs to do similar things that are done as in NMT, including downloading the SMT model and unpacking it into the right folder, and then deleting it from the S3 bucket.

**Comment by ddaspit** [comment]
@johnml1135 Can this issue be closed?
