### ISSUE TITLE
Already written text is not pretranslated if no trainOn books are specified

### ISSUE THREAD

**Issue by pmachapman** [sillsdev/serval#383]
#370 added the ability to pre-translate text that was previously translated. This works perfectly, if a user specifies the books to train on.

However, if no books are specified in `trainOn`, then the old behavior where only blank segments in the target are translated occurs.

For example the following build:
```json
{
    "id": "663935b2d3673074e65b4cbf",
    "url": "/api/v1/translation/engines/663935afd3673074e65b4cbb/builds/663935b2d3673074e65b4cbf",
    "revision": 9,
    "engine": {
      "id": "663935afd3673074e65b4cbb",
      "url": "/api/v1/translation/engines/663935afd3673074e65b4cbb"
    },
    "trainOn": [
      {
        "corpus": {
          "id": "663935b2d3673074e65b4cbe",
          "url": "/api/v1/translation/engines/663935afd3673074e65b4cbb/corpora/663935b2d3673074e65b4cbe"
        },
        "textIds": []
      }
    ],
    "pretranslate": [
      {
        "corpus": {
          "id": "663935b2d3673074e65b4cbe",
          "url": "/api/v1/translation/engines/663935afd3673074e65b4cbb/corpora/663935b2d3673074e65b4cbe"
        },
        "textIds": [
          "PHM"
        ]
      }
    ],
    "step": 0,
    "percentCompleted": 1,
    "message": "Completed",
    "queueDepth": 0,
    "state": "Completed",
    "dateFinished": "2024-05-06T20:08:56.786Z",
    "options": {
      "max_steps": 20
    }
  }
```

Returns the following USFM for https://qa.serval-api.org/api/v1/translation/engines/663935afd3673074e65b4cbb/corpora/663935b2d3673074e65b4cbe/pretranslations/PHM/usfm?text-origin=OnlyPretranslated:
```
\id PHM - Paipera Tapu Back Translation
\c 1
\v 1 Paul, a prisoner of Christ Jesus, and Timothy our brother,
\v 2
\v 3
\v 4
\v 5
\v 6
\v 7
\v 8
\v 9
\v 10
\v 11
\v 12
\v 13
\v 14
\v 15
\v 16
\v 17
\v 18
\v 19
\v 20
\v 21
\v 22
\v 23
\v 24
\v 25
```

**Comment by pmachapman** [comment]
This bug also occurs if the book selected for training is blank in the target, but has content in the source.

**Comment by Nateowami** [comment]
@ddaspit If `textIds` is null or not present, I can understand using "train on everything" as the default. However, if we send an empty array, it should be understood to mean "don't train on anything." We've already been supporting inferencing without training, so this behavior has produced a regression in Scripture Forge.

@pmachapman I'm guessing we could work around this without waiting for Serval. The current model is:

``` json
{
  "name": "string",
  "trainOn": [
    {
      "corpusId": "string",
      "textIds": [
        "string"
      ],
      "scriptureRange": "string"
    }
  ],
  "pretranslate": [
    {
      "corpusId": "string",
      "textIds": [
        "string"
      ],
      "scriptureRange": "string"
    }
  ],
  "options": {
    "property": "value"
  }
}
```

And I'm guessing what we're doing is sending `trainOn` with `textIds` properties set to `[]`. We could probably just not specify a corpus if it's empty anyway, and just send `"trainOn": []`?

**Comment by pmachapman** [comment]
> We could probably just not specify a corpus if it's empty anyway, and just send "trainOn": []?

Not sure - a question for @ddaspit or @johnml1135?

**Comment by ddaspit** [comment]
That is correct. If you send `"trainOn": []`, then Serval won't train on anything.

The current behavior is not intuitive. We will change it, so that if an empty array is specified for `textIds`, then we won't train on anything.
