### ISSUE TITLE
Cancelling SMT build hangs until engine is built then throws 404

### ISSUE THREAD

**Issue by Enkidu93** [sillsdev/serval#40]
During testing, I've observed that if I build an SmtTransfer engine and then attempt to cancel it, it doesn't interrupt the build process but waits til it's built then throws a 404 because there is no active build. Have you observed this, @johnml1135 ?

**Comment by ddaspit** [comment]
The main cause of this issue is that we are not checking the cancellation token often us when training an SMT model. I am reopening this issue, because it has not been addressed yet.

**Comment by johnml1135** [comment]
@Enkidu93 - has this been fully addressed?  I believe it has...

**Comment by johnml1135** [comment]
@ddaspit  has this been resolved?

**Comment by Enkidu93** [comment]
My apologies, @johnml1135. Somehow your earlier comment slipped under my radar. I'm happy to investigate this unless @ddaspit has already determined the answer (?).

**Comment by Enkidu93** [comment]
I can now verify that this has been addressed.
