### ISSUE TITLE
No way to clear or cancel a stuck SMT job

### ISSUE THREAD

**Issue by pmachapman** [sillsdev/serval#403]
I have an SMT job stuck on qa.serval-api.org that was been "active" for at least a week or two:
```json
{
  "id": "664ab3f0d3673074e6650b46",
  "url": "/api/v1/translation/engines/664ab331d3673074e6650b3d/builds/664ab3f0d3673074e6650b46",
  "revision": 292,
  "engine": {
    "id": "664ab331d3673074e6650b3d",
    "url": "/api/v1/translation/engines/664ab331d3673074e6650b3d"
  },
  "step": 106840,
  "percentCompleted": 0.55,
  "message": "Tuning translation model",
  "state": "Active",
  "options": {}
}
```
POSTing to https://qa.serval-api.org/api/v1/translation/engines/664ab331d3673074e6650b3d/current-build/cancel does not seem to clear its state (or cancel the job if it is still running - I don't believe it still is).

Is it possible to have SMT jobs that appear to have failed get cleared? Either automatically via a timer (i.e. if stuck in the same state for 24 or 48 hours?), or have the job "failed" when cancelled and no process is running any longer. Currently my only option is to delete the translation engine.

There maybe some bug that caused the SMT process to crash, or perhaps something else happened to cause the process to get unceremoniously killed? Rerunning the build may cause that error to manifest itself?

**Comment by johnml1135** [comment]
This issue will be resolved with the 1.5 release of Serval coming in a few weeks.  Yes, for now, I would just delete and recreate the engine.

**Comment by johnml1135** [comment]
This should be resolved.

**Comment by ddaspit** [comment]
How was this resolved?
