### ISSUE TITLE
Choice to always use source USFM for generating new USFM

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#405]
Currently the choice of whether to use source or target USFM as the template for inserting in the pretranslations is not given to the user.  This issue is to allow that choice to be made at the Serval level - this is a spin off from https://github.com/sillsdev/serval/issues/398 from @pmachapman's comments. 

Issues:
* I assume that the existing target verses may be able to be placed in the source USFM template - or will we only allow inserting pretranslations?
* Will this be a 5th option for "pretranslations only", etc., such as "pretranslations in source USFM", or will it be a separate field that can have the 4 options?
* Is this really needed or would better USFM handling and error visibility be the main issue?

**Comment by pmachapman** [comment]
Particular scenarios this could resolve:

**1. The target does not contain verse numbers matching the source.**

For example, one project contained a complete chapter in the source, the the target USMF for the chapter looked like:
```
...
\c 2
\v5 One verse completed
\c 3
...
```

**2. The target has different verse numbering than the source.**

For example:

 * The source has combined verses, i.e. 2-3, while the target has separate verse 1, verse 2, verse 3, etc.
 * The source has verse letters, i.e. 2, 2a, 2b, while the target just has verse 2

**Comment by johnml1135** [comment]
These are two different issues, that people may want to resolve differently.
1. To resolve the missing verses, it would seem intelligent to me to always fill in the verses if they are missing.  I don't see why people wouldn't want this functionality.  For non-scripture text, I can see why they may not want it.  I don't think that should be default.  This is now tracked in #414.

2. I also see value in "use source USFM as template" so that non-scripture text as well as verses ranges can be accurately converted.  We can still have the 4 options (preferExisting, etc.) but just pull out the target text into a set of rows that is (or is not) inserted into the source USFM structure.

**Comment by ddaspit** [comment]
One issue that we would need to resolve is the case where the target book is partially translated. If we force it to use the source in this case, then the existing verse text will be lost. If the target book is empty, then this will not be an issue.

**Comment by ddaspit** [comment]
The easiest and most flexible way to implement this is to add a new query parameter that allows use to specify if you want to use the source or target book.

**Comment by johnml1135** [comment]
Done - both pull requests are in your inbox.
