### ISSUE TITLE
Last verse blank in USFM in a specific translation engine

### ISSUE THREAD

**Issue by pmachapman** [sillsdev/serval#408]
For one of my translation projects (from Latin to English), the last verse in the USFM is always blank.

The USFM (https://qa.serval-api.org/api/v1/translation/engines/662e83d5d3673074e658b6db/corpora/662e83dfd3673074e658b6de/pretranslations/S3Y/usfm?text-origin=OnlyPretranslated) returns:
```
...
\v 66 Remove from me the way of iniquity: and out of thy law have mercy on me.
\v 67
```

While returning the pre-translations as text (https://qa.serval-api.org/api/v1/translation/engines/662e83d5d3673074e658b6db/corpora/662e83dfd3673074e658b6de/pretranslations/S3Y) returns:
```json
[
  {
    "textId": "S3Y",
    "refs": [
      "S3Y 1:66"
    ],
    "translation": "Remove from me the way of iniquity: and out of thy law have mercy on me."
  },
  {
    "textId": "S3Y",
    "refs": [
      "S3Y 1:67"
    ],
    "translation": "Praise ye the Lord, O all ye religious; give glory to the Lord the God of gods: for his mercy endureth for ever."
  }
]
```

It is the same for all other books in this translation engine.

I have checked previous pre-translations for the same translation engine, and can confirm that this bug occurred in April as well, and is not a new bug with the latest release of Serval on QA (for some reason I didn't notice previously).

**Comment by johnml1135** [comment]
Instinct - if there is no text at the end it will not start a verse text... Check it out.

**Comment by pmachapman** [comment]
> if there is no text at the end it will not start a verse text... Check it out.

Do you mean source text? My source and target look like:

![image](https://github.com/sillsdev/serval/assets/8665431/9664905e-d2ae-4095-8646-e25c70354e2a)

**Comment by bhartmoore** [comment]
What's the status here? Looks like maybe it's fixed and ready for release? Taeho's class at Payap has run into this issue over the weekend so I'm just adding this for additional examples/context: 

Student writes, "Currently our class are all facing the same problem which is the Book AI generated always occur the last chapter of the book missing the last verse, AI is always not be able to translate the last verse of the last chapter of the book. The examples are in attachment. The chapter 4 of Malachi V6 is missing and Book of Esther Chapter 10 V3."

![IMG_3936](https://github.com/sillsdev/serval/assets/127882639/b629e520-6461-4182-9cf0-d297865a6f8c)
![IMG_3937](https://github.com/sillsdev/serval/assets/127882639/14a8ff63-c3c4-4212-b12b-b6f0b865bdd4)

**Comment by ddaspit** [comment]
This has been fixed and will be shipped in the next Serval release.
