### ISSUE TITLE
Auto-add missing verses in target USFM

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#414]
We should just do this.  Spin off from #405.

Specifically, for verse text (not non-verse text), if there is a pretranslation available and a target USFM file, but the target USFM file only has a few verses, create the other verses in the appropriate locations and fill it in with the pretranslations.

**Comment by ddaspit** [comment]
We probably want this to be configurable. I don't think we should automatically mess with the structure of a target translation.

**Comment by ddaspit** [comment]
Let's hold off on implementing this until we get specific requirements from Scripture Forge.

**Comment by johnml1135** [comment]
This is not relevant for now.  https://github.com/sillsdev/serval/issues/405 is the resolution needed at this time.
