### ISSUE TITLE
Include Book Intro and first section heading in draft

### ISSUE THREAD

**Issue by bhartmoore** [sillsdev/serval#415]
Currently when a draft is generated through the Scripture Forge interface, the book intro and first section heading are omitted. We'd like to include these in the drafts. All other section headings in the book are translated. Screenshot from the SFDF project: 
![image](https://github.com/sillsdev/serval/assets/127882639/113505f2-b5d7-488b-961a-bba6d27a8e5a)

**Comment by johnml1135** [comment]
This looks like the #405 issue.  Likely the intro is not in the target USFM.

**Comment by bhartmoore** [comment]
That's certainly possible, but I think in this case the target contains an intro section and a heading for ch. 1. 
![image](https://github.com/sillsdev/serval/assets/127882639/f50521d5-ee6a-458a-b943-bae2fb38301c)

**Comment by johnml1135** [comment]
Can you upload the project files or include a link to the project in Serval?

**Comment by bhartmoore** [comment]
Thanks, John - this is their last build. It looks like we used LBS21 as the NT text for this test project and NIV11 as the training source. 
![image](https://github.com/sillsdev/serval/assets/127882639/8917e04b-5466-451d-b4c9-5cc20d1fa62e)

**Comment by bhartmoore** [comment]
It's also been reported for projects Ath (Athpariya), Lhr (Lohorung), Yak (Yakkha) and Yamphu (Yamphu). I don't believe I have access to see this diagnostic info for their last builds but can request it if needed. Here's the setup for the Ath project, and I can pull that for the others, as well. Let me know what would be most helpful to work with. 
![image](https://github.com/sillsdev/serval/assets/127882639/acd95b88-0f0d-4adc-80d7-e2ba16aebbac)

**Comment by bhartmoore** [comment]
Note that the \s1 is also being omitted. Separate issue maybe?

**Comment by ddaspit** [comment]
We can close this issue. It is not needed.
