### ISSUE TITLE
USFM ScriptureTag emtpyStack

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#416]
There is a weird un-reproducable bug from @Nateowami which has where:
```
\v 21 aaa
\q1 bbb
\q2 ccc
\c 10
\b
\s2 ddd <it breaks here>
```
breaks on the scripture tag.  Why?  It shouldn't.  It breaks in `ScriptureRefUsfmParserHandlerBase` when `_curElements` is Pop'd.  It is hard to reproduce (it will not reproduce itself if you copy and paste above) but at the end of the day, `EndParentElement` ends up removing the last of the `_curElement` stack which then leads to a crash.  The fix which should get rid of this type of error is to never allow it to be an empty stack.

**Comment by Nateowami** [comment]
Your description first says that this is "un-reproducable" and then later on calls it "hard to reproduce". Has it been reproduced? I can't be 100% certain that the file I sent you is the exact same as the file that caused the error for the user.

**Comment by johnml1135** [comment]
The file I had produced the error.  I was unable to reproduce it in test code, though the issue should be removed no matter what caused it.

**Comment by ddaspit** [comment]
I will take a look at this and see if I can figure out what is going on.

**Comment by ddaspit** [comment]
I figured out the root cause. The problem seems to be caused by some obsolete code that deals with the `\d` marker and should have been removed. I will submit a PR next week with a unit test case.

**Comment by Nateowami** [comment]
@johnml1135 Is this fix now on Serval live?
