### ISSUE TITLE
BSON representation of BSONID should be explicit

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#42]
For each class stored in the MongoDB, it should be:
```
public class MyClass
{
    [BsonId]
    [BsonRepresentation(BsonType.ObjectId)]
    public string Id { get; set; } = default!;
...
}
```

**Comment by johnml1135** [comment]
See here for explanation: https://stackoverflow.com/questions/38871416/difference-between-decorating-a-property-in-c-sharp-with-bsonrepresentationbson

**Comment by ddaspit** [comment]
This shouldn't be necessary, since a convention is already used to indicate that BSON representation is an ObjectId.
