### ISSUE TITLE
Better database indexing for pretranslations

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#422]
Based upon https://www.mongodb.com/docs/manual/tutorial/create-indexes-to-support-queries/#std-label-create-indexes-to-support-queries, we should use multi-indexing for pretranslations.  Specifically, it appears that we should use a multi-index of the engineId and the Scripture reference to be able to get the verses without having to scan all pretranslations.

**Comment by johnml1135** [comment]
@Enkidu93, this should help resolve the MongoDB warnings of "Query Targeting: Scanned Objects / Returned has gone above 1000".

**Comment by johnml1135** [comment]
@Enkidu93, would you be able to look at how best to resolve this?

**Comment by Enkidu93** [comment]
> @Enkidu93, would you be able to look at how best to resolve this?

Sure, I would love to check it out!
