### ISSUE TITLE
ClearML analytics - managing GPU capacity

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#423]
Build up a few scripts to look at historical GPU and CPU usage, separated by (if possible)
* Research
* Production jobs
* Onboarding
* Engineer-in-the-loop jobs
* Other testing

**Comment by Enkidu93** [comment]
Isn't this done, @johnml1135? Is there a PR that still needs to be reviewed?

**Comment by johnml1135** [comment]
This one is done - we see enough to manage capacity.
