### ISSUE TITLE
Empty book even though pretranslations exist

### ISSUE THREAD

**Issue by Enkidu93** [sillsdev/serval#445]
Bethany brought up this issue after she received a complaint about Exodus being empty. After investigation, the pretranslations do exist, yet regardless of what `textOrigin` is set to, the generated usfm book is empty (all except the line `\id EXO - Mengen Bible` which is in the original target EXO).

'engine_id': '669fb1e23070239788c5a930'

**Comment by bhartmoore** [comment]
Verified the configuration and request settings with the user; he's sending the request correctly. He's retrying the draft after recreating the blank source book (EXO) with the USFM structure and will let us know results.

**Comment by bhartmoore** [comment]
User confirms that he received a good draft of EXO after creating a blank PT book with all the verses in the target project.

**Comment by Enkidu93** [comment]
> User confirms that he received a good draft of EXO after creating a blank PT book with all the verses in the target project.

OK! Glad to hear that at least he was able to get a proper draft in his hands (Praise the Lord!). I will keep investigating since I think this should be a circumstance in which Serval is robust enough to provide a draft.

**Comment by ddaspit** [comment]
Once SF starts using the new feature (#405) to force Serval to return USFM with the source book as the template, then it will no longer be necessary to add verse markers to the empty target book.
