### ISSUE TITLE
Another Stack Empty USFM bug

### ISSUE THREAD

**Issue by Enkidu93** [sillsdev/serval#449]
Fails with a stack empty on this line, column 4:
`\q //Amo matipi̱na̱waka̱n iga timelaꞌtajtowaj.//`

(I have the full usfm file locally for testing)

**Comment by johnml1135** [comment]
@Enkidu93 - have you had any progress on this?

**Comment by Enkidu93** [comment]
> @Enkidu93 - have you had any progress on this?

No, not yet. Trying to get the other PR through first.
