### ISSUE TITLE
"500 Internal Server Error" for invalid "files/{id}" request

### ISSUE THREAD

**Issue by mpelley** [sillsdev/serval#453]
If I send a GET request to "files/bogus_id" or "files/00000000", I expected a "404 Not found" error.  Instead I get a "500 Internal server error".
If I send a GET request to "files/000000000000000000000000" , I get the expected a "404 Not found" error.
I should never get a "500 Internal server error" because of invalid user input.

**Comment by Enkidu93** [comment]
Good catch. I've been aware of this issue for a bit (although I thought it was giving a 400/Bad Request not a 500) and keep forgetting to address it.

**Comment by mpelley** [comment]
I still get the "internal server error" when I use a garbage id for getting a webhook.  For example "hooks/bad_id".  

@johnml1135: Should I reopen this issue or submit a new one?

**Comment by Enkidu93** [comment]
> I still get the "internal server error" when I use a garbage id for getting a webhook. For example "hooks/bad_id".
> 
> @johnml1135: Should I reopen this issue or submit a new one?

@mpelley, sorry, this has been 'completed' in the sense of 'added to the main branch' but it hasn't been deployed yet (neither to QA nor to production, I don't think - @johnml1135 can correct me - I could be wrong). Is is still an issue for the data files and engines - or just webhooks now - because that might indicate that an incomplete fix may have been pushed or that this is a different issue? Thanks!

**Comment by mpelley** [comment]
@Enkidu93 This is no longer an issue for data files, but just webhooks.  (Oops, I need to add a test for the translation engines.)

**Comment by mpelley** [comment]
I just now tried it with translation engines.  I get "internal server error" instead of the expected "not found".

**Comment by Enkidu93** [comment]
OK, looks like my fix isn't deployed yet then, @mpelley - it should fix the issue across all of them: files, engines, etc. I don't understand why it would be working for data files now though :thinking:.
