### ISSUE TITLE
Multiple Serval failures

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#457]
There have continued to be a steady stream of failing Google Chat messages from Serval (5 a day?).  These should be investigated and addressed so that either (1) the underlying issue is addressed or (2) the logging is reconfigured to no longer make the Google chat message.

**Comment by Enkidu93** [comment]
I think all of these alerts are from/connected to #449, #450, and #453.

**Comment by Enkidu93** [comment]
I'm going to close this since I'm fairly confident that the recurring alerts we've received are the result of issues tracked above.
