### ISSUE TITLE
Don't parse books that aren't selected

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#460]
The USFM parser shouldn't crash on non-selected books.

This should never happen:
```
  {
    "id": "789"
    "revision": 2,
    "engine": {
      "id": "xyz"
    },
    "trainOn": [
      {
        "corpus": {
          "id": "abc"
        },
        "scriptureRange": "MAT;MRK;LUK;JHN;ACT;ROM;1CO"
      }
    ],
    "pretranslate": [
      {
        "corpus": {
          "id": "123"
        },
        "scriptureRange": "2CO"
      }
    ],
    "step": 0,
    "message": "An error occurred while parsing the text 'XXB` in project 'MTR'. Verse: XXB 4:0, line: 88, column: 5, error: 'Stack empty.'",
    "state": "Faulted",
    "dateFinished": "2024-08-12T05:43:52.712Z",
    "options": {}
  },
```

Notice how the crash happened on XXB, even though XXB was never selected for the `scriptureRange`.

**Comment by johnml1135** [comment]
We should test this - one possible way is to have the parser always throw an exception - and to have a passing case where no books are selected and a failing where some books are selected.

**Comment by Enkidu93** [comment]
Alright, I see what's happened here - looks like Damien's work was lost because of some concurrent PRs. I'll put in a fix asap.
