### ISSUE TITLE
Job says pending in Serval, but is actually completed on ClearML

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#480]
After restarting the servers, somehow Serval figured it out and moved it to completed.

**Comment by tmcoder2** [comment]
Is there any plan/opportunity for Root Cause Analysis?

**Comment by johnml1135** [comment]
Yes - absolutely :-)

**Comment by johnml1135** [comment]
For the time being, I will assume that the lock issue was causing this.  If it happens again, we can dig into it further.
