### ISSUE TITLE
429 (TooManyRequests) Responses from ClearML

### ISSUE THREAD

**Issue by Enkidu93** [sillsdev/serval#492]
In recent weeks, we've seen exceptions thrown from the `ClearMLMonitorService` regarding a failure to parse responses from ClearML. John added improved logging and the issue has reoccurred, so I peeked at the logs and the unexpected responses are 429s. Do we need to poll more infrequently and/or change our http client retry strategy? The response we're getting from ClearML does not seem to specify a `Retry-After` unfortunately. I haven't yet found any information regarding the rate-limiting on ClearML - maybe it's worth reaching out to them (?).

**Comment by johnml1135** [comment]
We could try spitting out the header as well:
https://stackoverflow.com/questions/75302783/how-do-i-catch-the-http-error-429-retry-after-time-in-a-try-except-scenario

**Comment by Enkidu93** [comment]
> We could try spitting out the header as well: https://stackoverflow.com/questions/75302783/how-do-i-catch-the-http-error-429-retry-after-time-in-a-try-except-scenario

Oh, good point!

**Comment by ddaspit** [comment]
It looks like we are making extra calls to `GetTasksByIdAsync`. We are currently calling it for every engine type when we only need to call it once.

**Comment by ddaspit** [comment]
We should remove the extra calls and increase the polling timeout by a bit. Hopefully that will be enough to fix this issue.

**Comment by johnml1135** [comment]
I wonder - did you see the messages from IDX on the ClearML channel?- it could be that they are the ones causing the issue.  It may be that our request comes in right when they are in the middle of DoS'ing the server and we get the "TooManyRequests" error.  It shouldn't happen because we are using different user creds than IDX, but it could still be the case.  Either way, we should elegantly handle it.

**Comment by Enkidu93** [comment]
> I wonder - did you see the messages from IDX on the ClearML channel?- it could be that they are the ones causing the issue. It may be that our request comes in right when they are in the middle of DoS'ing the server and we get the "TooManyRequests" error. It shouldn't happen because we are using different user creds than IDX, but it could still be the case. Either way, we should elegantly handle it.

I don't think I'm on that channel. Could you add me or point me there?

Also, @johnml1135, unless you're already working on this one actively, I think I'll go ahead and do this while I'm waiting for review. We've been getting *a lot* of these errors.

**Comment by johnml1135** [comment]
Go for it.

**Comment by Enkidu93** [comment]
Waiting to see if once PR #504 is on QA, the errors stop appearing.

**Comment by johnml1135** [comment]
This resolved it: https://github.com/sillsdev/serval/issues/524.
