### ISSUE TITLE
Investigate replacing SIL.DataAccess with EF Core

### ISSUE THREAD

**Issue by ddaspit** [sillsdev/serval#494]
In the last year, Mongo has released a [MongoDB EF Core Provider](https://github.com/mongodb/mongo-efcore-provider). [EF Core](https://learn.microsoft.com/en-us/ef/core/) is the preferred data access library for ASP.NET Core. SIL.DataAccess was necessary, because there was no EF Core provider for MongoDB. Now that there is, it would probably be worth investigating replacing SIL.DataAccess altogether.

**Comment by johnml1135** [comment]
https://www.mongodb.com/docs/entity-framework/current/limitations/

It appears that there are significant limitations to EF core right now, including not being able to use Select().  I see no drawback in holding off for right now until 1 or 2 more versions come out.

**Comment by johnml1135** [comment]
As per conversation with Damien, although we are using Select(), we are using it after we already grab the data from the database.  There are no perceived issues with migrating to EF Core.

**Comment by johnml1135** [comment]
Can we replace the entire IRepository interface with EF Core?  Can we address the other issues with EF Core?
* ArrayFilterDefinition
* Subscribe to changes
* CRUD

**Comment by mudiagaobrikisil** [comment]
Looked at it. So far, with EF Core, we can handle CRUD, transactions and subscribe to changes. I am looking at the ArrayFilterDefinition. Also, when you say other issues with EF Core, are there specific issues you have in mind or we have encountered in time past?

**Comment by johnml1135** [comment]
Let's close this for now and open up an new issue to investigate it when the next version of EF Core comes out.
