### ISSUE TITLE
Filtering on pretranslations not working!

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#514]
We're putting all verses into `pretranslate.src.json`!  This is causing issues.

**Comment by johnml1135** [comment]
@Enkidu93  - also, if a corpora is specified for pretranslation or training, then all other corpora should not be used.  Currently I believe the logic is "use all".  This is unintuitive.

**Comment by Enkidu93** [comment]
> [@Enkidu93](https://github.com/Enkidu93) - also, if a corpora is specified for pretranslation or training, then all other corpora should not be used. Currently I believe the logic is "use all". This is unintuitive.

@johnml1135, that could be unintuitive, I agree. Wasn't that how it already worked though with the non-parallel corpora? I think it was conceived of more as specifying a set of filters that operate on all of the associated corpora than positively specifying all data; is that right?

**Comment by johnml1135** [comment]
Multi-corpora filtering moved to #516.
