### ISSUE TITLE
Add Native support for Keyterm files in Serval 

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#52]
This may be implemented in Scripture Forge - but may require some updates in Serval for support. TBD.

**Comment by johnml1135** [comment]
Specifically, this will be uploading csv or tsv (or other) files into SF using a drag and drop functionality.  These files will be associated with a project in SF.  These files will then be prepped and uploaded to Serval using the standard text file format.

**Comment by pmachapman** [comment]
We currently upload a file from SF to Serval called [biblical_terms.txt](https://github.com/sillsdev/serval/files/12188290/biblical_terms.txt), which is uploaded for the source and target, if present. Is this format suitable?

Note how some words have two definitions, and how some definitions are synonyms or have prepositions, or are numbered (this is matchings the biblical terms in Paratext)

**Comment by johnml1135** [comment]
@pmachapman - to answer your questions:
* The biblical_terms would have to be split up into a source and target files before being uploaded to Serval.
* If there are multiple glosses, they can made into multiple entries.
* We currently don't have a good way of dealing with asterisks in key terms.  Really, we would need more info, like how the root word would be translated in various contexts.  Since we don't have that currently, just stripping the asterisks should be fine enough.
* As for numbered words, if the words have numbers in the source text, then keep the numbers in the glosses, else, remove them.

Example:

**Comment by ddaspit** [comment]
[Here](https://github.com/sillsdev/silnlp/blob/a24a82bed3bbb020386e068de92bb914d21b54cd/silnlp/common/paratext.py#L286C9-L286C9) is the function that we use to process Biblical term glosses in silnlp. I would also only include proper nouns. I don't think any other Biblical terms will be useful.

**Comment by pmachapman** [comment]
Did the implementation of Biblical Terms in #167 fix this issue, or do we need another wordlist interface?

**Comment by johnml1135** [comment]
@ddaspit  - can you comment on this?

**Comment by johnml1135** [comment]
@pmachapman - this is the processing done in SILNLP:
``` python
def _process_gloss_string(gloss_str: str) -> List[str]:
    match = re.match(r"\[(.+?)\]", gloss_str)
    if match is not None:
        gloss_str = match.group(1)
    gloss_str = gloss_str.replace("?", "")
    gloss_str = clean_term(gloss_str)
    gloss_str = strip_parens(gloss_str, left="[", right="]")
    gloss_str = re.sub(r"\s+\d+(\.\d+)*$", "", gloss_str)
    glosses = re.split("[;,/]", gloss_str)
    glosses = unique_list([gloss.strip() for gloss in glosses if gloss.strip() != ""])
    return glosses
```

Can you comment on whether SF is doing similar processing?  Or, by contrast, should the long term plan be for Serval to do this processing and SF just give Serval the Biblical Terms list?

**Comment by pmachapman** [comment]
@johnml1135 We do most of that processing. The ones we do not do are stripping question marks:
```
 gloss_str = gloss_str.replace("?", "")
```
and removing square brackets:
```
gloss_str = strip_parens(gloss_str, left="[", right="]")
```
(I was not aware that these were supported syntax for renderings? - I cannot see these in the Paratext guide for renderings)

I think SF's implementation should be sufficient for MVP, unless you disagree?

I think mid to long term when you add processing of the USFM from SF, passing the XML file through too would be the best solution?

**Comment by johnml1135** [comment]
I agree - let's leave what SF has for the MVP - we may be able to push this functionality into Serval in the future along with better support for Paratext projects, etc.

**Comment by johnml1135** [comment]
Note: this issue is for the implementation of this functionality in Serval proper in conjunction with Paratext zip files.

**Comment by johnml1135** [comment]
This should be implemented directly in Serval to allow for the same quality models to be build with just uploading a Paratext zip.

**Comment by johnml1135** [comment]
Hmm - yes.  It would be parsing the Keyterm file[s] out of the Paratext project and prepping them in a standard way.  I don't think anything would have to be done in Serval.

**Comment by Enkidu93** [comment]
So for the key terms, these would be included for pretranslation, not training, correct? I assume we'd like this to be toggleable? @johnml1135

**Comment by ddaspit** [comment]
I think it makes sense to add a property that enables/disables this functionality.

**Comment by ddaspit** [comment]
Oh, I misunderstood. There is no need to pretranslate key terms. I thought you were talking about a flag to include or not include key terms in the training data.

**Comment by Enkidu93** [comment]
OK, I misunderstood then. Originally, I thought they were for training only, but then I was confused when I saw the structure. Is it just that the key terms will be populated in the source language by default and possibly have entries in the target? In the test project I was working with, the terms were in Hebrew (which was not the source language) and you could manually add entries in the target. What am I missing?

**Comment by Nateowami** [comment]
What are you actually planning on _doing_ with key terms? Using them as training data?

**Comment by johnml1135** [comment]
Keyterms are usable through SF currently.  Implementing the functionality for Serval directly forked to a new issue.
