### ISSUE TITLE
Get pretranslations for parallel corpora

### ISSUE THREAD

**Issue by Enkidu93** [sillsdev/serval#522]
The pretranslation service does not handle the new parallel corpora. This needs to be fixed ASAP. Also, there's the added complexity of multiple potential sources (i.e., where do we get the usfm from - always the first source?).

**Comment by johnml1135** [comment]
Would this fix it #525?

**Comment by Enkidu93** [comment]
The USFM portion of retrieving pretranslations still does not work like Peter noticed.

**Comment by johnml1135** [comment]
The first portion was fixed.  More do to in other issues.
