### ISSUE TITLE
Regression: Already written text is not being pre-translation on Serval QA

### ISSUE THREAD

**Issue by pmachapman** [sillsdev/serval#536]
On Serval QA, any text that has already been entered by the user is not being pre-translated. This is a regression of #370.

Compare this pre-translation on Serval Prod:
![Image](https://github.com/user-attachments/assets/12da04e3-4758-4e3c-8a85-c8b3f9f9982e)

To Serval QA:
![Image](https://github.com/user-attachments/assets/a8b4c937-1ff5-4280-8598-6413a2a32138)

Both builds had the same source and target, and were both set to train on MRK and pre-translate JHN. The translations were generated with only 20 `max_steps`.

Pre-translation of already written text is an important feature of Serval (and was originally requested by users), so I would classify this as a blocker for QA going to production.

**Comment by johnml1135** [comment]
This is related to #533 - We can discuss at the meeting exactly how to handle this.

**Comment by johnml1135** [comment]
@pmachapman  - is this now resolved?
