### ISSUE TITLE
Duplicated Key Terms

### ISSUE THREAD

**Issue by Enkidu93** [sillsdev/serval#538]
Michael reported that in an English-to-Indonesian project, the automatically added KBTs were duplicated:

"For instance, in the train.src.txt / train.trg.txt files that were constructed here from those default term renderings, there are many many duplicates:

4 mappings of Joseph --> Yusuf
4 mappings of Joram --> Yoram
4 mappings of Jezreel --> Yezreel
3 mappings of Jotham --> Yotam
and on and on ...

This duplication is probably not helpful for fine-tuning."

**Comment by johnml1135** [comment]
@Enkidu93  - do you know the origin of this?  Do you know if it will be resolved through the updates that you are making?

**Comment by Enkidu93** [comment]
> [@Enkidu93](https://github.com/Enkidu93) - do you know the origin of this? Do you know if it will be resolved through the updates that you are making?

I suspect this might be to do with the fact that some PN refer to multiple real-world entities so they may have multiple entries per entity. It's easy enough to do a Distinct on the all the PNs. That might be simplest since I suspect that on occasion (especially in languages that have a longer tradition of Bible translation) that there may be different renderings for the same name when it refers to different entities. For example, Greek Iakob can refer to both Jacob and James in English.

**Comment by Enkidu93** [comment]
> > [@Enkidu93](https://github.com/Enkidu93) - do you know the origin of this? Do you know if it will be resolved through the updates that you are making?
> 
> I suspect this might be to do with the fact that some PN refer to multiple real-world entities so they may have multiple entries per entity. It's easy enough to do a Distinct on the all the PNs. That might be simplest since I suspect that on occasion (especially in languages that have a longer tradition of Bible translation) that there may be different renderings for the same name when it refers to different entities. For example, Greek Iakob can refer to both Jacob and James in English.

I dug into this, and yes, it looks like what I described above is what's causing the issue. I think the best strategy would be to deduplicate per source + target segment (since the term ids are different per unique entity, not per spelling). That could happen either in Serval or the terms parser itself.

**Comment by johnml1135** [comment]
I am inclined to do it in machine.  I believe all uses would be for NLP tasks, and the de-duplication would be an asset for all use cases (that I can imagine).

**Comment by Enkidu93** [comment]
> I am inclined to do it in machine. I believe all uses would be for NLP tasks, and the de-duplication would be an asset for all use cases (that I can imagine).

The issue is that on the Machine side we're working with more than just source + target: There's still a row ref that maps to that particular term id. I could envision circumstances outside our NMT training use case in which we might like a corpus of all the terms with their proper term ids. I don't know. What do you think, @ddaspit?

**Comment by ddaspit** [comment]
@Enkidu93 I agree. The duplication issue is specific to a parallel corpus of key terms that is used to train model. There are use cases where you would want to get the complete list of key terms.
