### ISSUE TITLE
SF: Train on one translation, translate off of another

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#54]
For some projects, we may want to fine tune NLLB from one set of translations while inferencing off of a different translation.  For training, the back translation may also be one of the best translations.  This should already be supported by Serval (with the files and corpora structures) - it would just need support from Scripture Forge.

**Comment by pmachapman** [comment]
> This should already be supported by Serval

Just to confirm, this is the "trainOn" property of the JSON BuildConfig, where another corpus is specified?

**Comment by ddaspit** [comment]
Yes, that is correct.

**Comment by pmachapman** [comment]
This was add into Scripture Forge in sillsdev/web-xforge#2185, and published in version [5.0.0](https://github.com/sillsdev/web-xforge/releases/tag/SFv5.0.0).

See [SF-2340](https://jira.sil.org/browse/SF-2340) for details.
