### ISSUE TITLE
Bugsnag.AspNet.Core has dependencies on deprecated/vulnerable packages

### ISSUE THREAD

**Issue by ddaspit** [sillsdev/serval#544]
`Bugsnag.AspNet.Core` hasn't been updated in a couple of years. I don't know if we can expect Bugsnag to fix the issues any time soon. We should consider removing the dependency and providing our own implementation that uses the `Bugsnag` library directly.

**Comment by johnml1135** [comment]
This is related to: https://github.com/bugsnag/bugsnag-dotnet/issues/170.
