### ISSUE TITLE
The parallel Corpus database holds onto old Filename when the file is updated

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#547]
It is copied to Corpus ... and then to Parallel Corpus ... and then the file is updated (and the filename changes) and then - poof!  it stops working!

**Comment by johnml1135** [comment]
Option 1: when updating a file, after the new file is written, replace the old one with a link to the new one.
Option 2: Redo the data structures to actually reference the main DataFile, not their own copy.
Option 3: Keep track of where each file is used and when it is updated, update all of the other places it is used as well.

@ddaspit and @Enkidu93   - what do you think?  1 is the simplest and 2 is the most elegant.

**Comment by johnml1135** [comment]
OPtion 2: and call it DataFileReference, not DataFile.

**Comment by ddaspit** [comment]
We should use option 1: publish a data file updated message to the mediator. See `DataFileDeleted` for an example.

**Comment by ddaspit** [comment]
Now that I looked at the code a bit more. I see that there are actually two issues.

1. In Serval.DataFiles, the `CorpusFile.File` property is a `DataFile`. That is incorrect. Unfortunately, I missed it in the code reviews. It should hold the ref id to the `DataFile` instance. The property should be renamed to `FileRef` and take a string. This is John's option 2.
2. When the data file is updated, the corresponding `CorpusFile` in Serval.Translation is not updated. We should use John's option 1 to fix this. We publish a data file updated message to the mediator, just like we do when a data file is deleted.

**Comment by johnml1135** [comment]
@ddaspit, what do you think of the solution that I coded? I did a complete option 2.  There may be a cleaner way to do this, but I think that having one source of Truth for the file name makes the most sense to me.
