### ISSUE TITLE
Transaction ID per API call

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#58]
For traceability and logging.

**Comment by johnml1135** [comment]
And appropriate tooling for traceability, etc.

**Comment by ddaspit** [comment]
We want to export the traces to Prometheus. Unfortunately, it looks like the [Prometheus Exporter](https://opentelemetry.io/docs/instrumentation/net/exporters/#prometheus-experimental) is experimental. OpenTelemetry recommends using the OTLP exporter instead. This would require that we run an instance of the OpenTelemetry Collector in the Kubernetes cluster to send the traces to Prometheus.

**Comment by ddaspit** [comment]
@johnml1135, where should the traces go?

**Comment by Enkidu93** [comment]
> We want to export the traces to Prometheus. Unfortunately, it looks like the [Prometheus Exporter](https://opentelemetry.io/docs/instrumentation/net/exporters/#prometheus-experimental) is experimental. OpenTelemetry recommends using the OTLP exporter instead. This would require that we run an instance of the OpenTelemetry Collector in the Kubernetes cluster to send the traces to Prometheus.

Yeah, I noticed that. Are there any other solutions? Maybe [this](https://github.com/prometheus-net/prometheus-net) (I'd have to look in more detail). Is there a reason we can't dump it to the console and let Prometheus sort it out from there haha.

**Comment by ddaspit** [comment]
I'm not an expert in these things. @johnml1135 definitely knows more than me. It looks like Prometheus is primarily used for metrics. I am most interested in using OpenTelemetry for distributed tracing. It sounds like we need some kind of distributed tracing backend to correlate traces across different services. [Jaeger](https://www.jaegertracing.io/) seems to be the most commonly used system. [Here] is an article in the .NET documentation for setting up OpenTelemetry. It uses the Prometheus for metrics and Jaegar for tracing.

**Comment by Enkidu93** [comment]
I was hoping @johnml1135 might weigh in as well to avoid doing work that might be for naught, but I'll go ahead an move this direction unless I hear otherwise.

**Comment by ddaspit** [comment]
For now, we can use the console exporter and figure out the distributed tracing backend later.

**Comment by Enkidu93** [comment]
So pretty much what I did [here](https://github.com/sillsdev/serval/compare/main...add_open_telemetry_%2358)? Would we want to instrument things with greater granularity? And extend this to Machine as well I presume?

**Comment by johnml1135** [comment]
@Enkidu93 - I looked into this a bit but not too in depth.  We can talk a bit to strategise.

**Comment by ddaspit** [comment]
@Enkidu93 Yeah, that looks good. We also want to instrument the Mongo driver. See [this](https://github.com/jbogard/MongoDB.Driver.Core.Extensions.OpenTelemetry/issues/10#issuecomment-1540047896) comment for more details. And, yes, we want to do the same for Machine.
