### ISSUE TITLE
Punctuation currently from NMT just adds spaces - this is annoying

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#62]
How can we address this?  Can we get punctuation data from Paratext and interpret it?  Can Serval intuit it from the training data using basic statistical methods?  Can we use the Paratext puctuation guesser if it is independent and can be added?

**Comment by johnml1135** [comment]
Let's just try to spit out a "good enough" algorithm right now:
Background/objectives:
* Formal SMT and NMT are not needed - just definition of "words", "punctuation" and "whitespace" as well as frequency of how they fall together
* We don't need 100% - anything is better than the 0% we are dealing with now
* Some languages don't have "words" or "whitespace" at all.

An algorithm:
* Determination 1: is there whitespace?  If there are no whitespaces between characters (not punctuation), i.e., less than 1 per 100 in the target when there are over 20 characters in a row, than yes - mush it all together. 
* ...

**Comment by johnml1135** [comment]
Is this a real issue - I need to find an example of this happening.

**Comment by ddaspit** [comment]
I don't quite understand what the issue is. Can you give more explanation?

**Comment by johnml1135** [comment]
@ddaspit, I believe that Machine.py is returning pretranslations like: "In the beginning was the Word , and the Word was God , and the Word was with God ." - adding spaces on both ends of the punctuation.

**Comment by ddaspit** [comment]
That is weird. This is only happening on Machine.py and not silnlp?

**Comment by johnml1135** [comment]
I haven't seen this again.  I am going to close it for now.  If we see the behavior we can capture it and reopen this issue.

**Comment by Enkidu93** [comment]
This issue has reappeared for me, but it's because my source has that odd punctuation (this is the data I was given by Peter). I'm wondering if this was the cause originally as well.

**Comment by johnml1135** [comment]
Can you upload some examples (of inputs and outputs)?  Is it something that NLLB does?  Does it not do a good job of dealing with odd punctuation?

**Comment by Enkidu93** [comment]
I don't know that this should be reopened. I'm saying that I witnessed something similar but it's because I had the same odd formatting in my source. This source came from Peter, and I imagine the issue he (or others) noticed might have the same cause.

**Comment by ddaspit** [comment]
This doesn't need to be reopened. This is simply the fine tuned model mimicking the data.
