### ISSUE TITLE
Expose application version through new endpoint

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#68]
This may be able to be put on a health check.  It may already be possible.  I should be able to ask Serval - what version are your various components?

**Comment by johnml1135** [comment]
This would be needed for https://github.com/sillsdev/silnlp/issues/179 - to enable auto-version grabbing of Serval to verify versions tested.

**Comment by Enkidu93** [comment]
Define "various components". What services or libraries would we need to check? A health check emendation is certainly feasible.

**Comment by johnml1135** [comment]
Ideally, the docker images of the kubernetes deployment.  I wonder if this could be done through this: https://github.com/kubernetes-client/csharp?  This is moderate to low priority.

**Comment by johnml1135** [comment]
Done - https://github.com/sillsdev/serval/pull/238.
