### ISSUE TITLE
Document echo engine in Swagger

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#72]
Do it - and how and why to use it.  It has a basic statement, but needs something more complete - which endpoints it covers (a full coverage of SMT and NMT endpoints - giving back the data).

**Comment by Enkidu93** [comment]
On it!

Do you want the Echo engine to cover the word graph endpoint? If so, how? Just a simple word graph with 1.0 confidence arcs that move along the series of words of the input segment? I noticed that this endpoint is missing.

**Comment by johnml1135** [comment]
Yes, adding the word graph - we will want to support all endpoints with echo (when feasible).   The 1.0 confidence arcs should be fine - if we want to do more in-depth testing of the word graph, we would want to use real data, not echos or synthesized (at least, not right now).
