### ISSUE TITLE
Refactor SMT and NMT build 

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#73]
From a review:

This code should really be refactored into a few different function calls.  If I am correct, this is invoked when a ClearML build is throwing exceptions - it is cleanup code and then the exception is passed on.  Why not have

`catch (Exception e) {CleanupBrokenBuild(); throw e}`

And then refactor a lot of other portions of this function.  At least all the error handling should be able to be put into different functions.  There is a good argument for preserving the main flow of building in one function. A full refactor may look like:
```
RunAsync(...){
   try{
     InitializeTask();
     while(true){
        CheckForCancellation();
        status = GetStatus();
        switch (status){
          case 1: ...
        }
    }
    FinalizeCompletedJob();
  }
  catch ...
```

**Comment by Enkidu93** [comment]
I think the issue has been satisfactorily completed in https://github.com/sillsdev/machine/pull/101. The massive methods of the previous iteration are gone, and large - but not intolerably large - methods have taken their place.
