### ISSUE TITLE
Echo cancelled

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#74]
"\u001b[40m\u001b[32minfo\u001b[39m\u001b[22m\u001b[49m: Grpc.Net.Client.Internal.GrpcCall[3]\n      Call failed with gRPC error status. Status code: 'Cancelled', Message: 'gRPC call disposed.'.\n"

What is happening here?  This, I believe, is the issue @Nateowami  is seeing.

**Comment by Enkidu93** [comment]
My guess is a "using" somewhere it shouldn't be. You want me to check it out? Or do you have it?

**Comment by johnml1135** [comment]
I’m going to see if I can dig into it tonight or tomorrow morning. I have nothing else pressing so I should be able to resolve this one.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by johnml1135** [comment]
The k8s deployment did not mount the volume - which caused the pretranslation to fail.  It needed to share the volume with serval to get the files to "echo" back.
