### ISSUE TITLE
SF suggestions doesn't work with very long segments

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#76]
There is something limiting this - for very long verses something pops up and says "this verse is too long for suggestions."  Can we fix/resolve this?

**Comment by ddaspit** [comment]
When a source segment is too long, decoding can take a long time. We put in a hard limit of 200 words in order to be able to generate suggestions for a segment. If we increased the CPU on the server, then we might be able to increase the limit a bit.

**Comment by johnml1135** [comment]
The limit of 200 tokens is actually a aspect of the of NLLB 200 itself.  I don’t think we can extend the token limit meaningfully, but rather we should split up the long segments.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ddaspit** [comment]
Actually, in this case, I was referring to the SMT model, but yes, you are correct NLLB also has a limit of 200 tokens.

**Comment by johnml1135** [comment]
Sorry, I was misunderstanding the context.

**Comment by johnml1135** [comment]
If the CPU is the main thing limiting the word graph, I would be more inclined to pay for more CPU. A few hundred dollars a year is worth the increased performance. What do you think?

**Comment by johnml1135** [comment]
We can also use grafana to measure the word graph performance in production.

**Comment by ddaspit** [comment]
We would need to do testing to see how much we could increase the limit. At this point, SMT suggestions are not being used very much, so it isn't a priority to increase this limit.

**Comment by johnml1135** [comment]
This issue is related to https://github.com/sillsdev/machine.js/issues/19.  After this bug is fixed, it may not be a big issue anymore.
