### ISSUE TITLE
Prometheus http endpoint monitoring and alerting

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#83]
Duration of http requests?  500 codes?  How can we get access to this data to query and to alert from.  Not logs, but http requests.

**Comment by johnml1135** [comment]
For getting CPU loading: `rate (container_cpu_usage_seconds_total{image!="", namespace="serval"}[5m])`  We can alert on anything over 80% for more than 1 hour - for serval-api, mongo, and machine (not the job engines).

**Comment by johnml1135** [comment]
@ddaspit - what do you think about adding this endpoint for metrics on the serval-api server (HTTP only): 
https://github.com/prometheus-net/prometheus-net#aspnet-core-http-request-metrics?  It looks to be the easiest way to collect http metrics to serval.  A few thoughts:
* It could be enabled through an environment variable such as ENABLE_HTTP_METRICS
* We could then use it for setting up alerts, monitoring overall usage and (I believe) usage by client.

**Comment by ddaspit** [comment]
I think we should consider using [OpenTelemetry](https://opentelemetry.io/) to instrument Serval for [metrics](https://opentelemetry.io/docs/concepts/signals/metrics/). It has [.NET libraries](https://opentelemetry.io/docs/instrumentation/net/) available and sounds like it supports Kubernetes and Prometheus.

**Comment by johnml1135** [comment]
Added.  Will add alerts as needed.
