### ISSUE TITLE
Add queue depth status per build

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#89]
Peal off from #44.

Add queue depth functionality to new Machine-server thread which would:
* Every 10 seconds check the ClearML queue, the hangfire queue and if any hangfire queued jobs have been cancelled.
* Report queue depth to serval for all queued jobs, including clearml-queued.
* This will avoid needing 50 threads with SubscribeForCancellation

**Comment by Enkidu93** [comment]
I think this task needs to be put on hold until Damien finishes his exploratory work with removing the Hangfire queue etc.

**Comment by Enkidu93** [comment]
Addressed here: https://github.com/sillsdev/machine/pull/110.
