### ISSUE TITLE
Build status min rev documentation

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#90]
Peal off from #44.
Webhooks instead of polling for build status - or doing the quasi-webhook of using minrevision+1.  The existing functionality does not need to be removed, but the new functionality can be added and SF can move to it.

**Comment by Enkidu93** [comment]
Let's just stick with long-polling but document this decision in Swagger.

**Comment by Enkidu93** [comment]
Fixed here: https://github.com/sillsdev/serval/pull/156
