### ISSUE TITLE
Add a "buildName" optional parameter when building engine

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#92]
When making a build (SMT/NMT/etc.) add a new parameter called `buildName`.  This will be treated like `name` for the engine or file and will be returned whenever anything is requested for it (build status, future webhooks, etc.).  This parameter should be optional.
  This is specifically helpful for SF to know which project needs the message when build status webhooks are implemented - they can put some form of SF project ID in the field and not need to make an extra database query/mapping.

**Comment by johnml1135** [comment]
Related to #90.

**Comment by Enkidu93** [comment]
Fixed here: https://github.com/sillsdev/serval/pull/131
