### ISSUE TITLE
Serval incorrectly returns a 404 when there are no pretranslations

### ISSUE THREAD

**Issue by ddaspit** [sillsdev/serval#96]
When the pretranslation endpoints are called and there are no pretranslations, then Serval incorrectly returns a 404 error. The `pretranslations` resource is a collection and should always exist as long as the engine exists. It is simply an empty collection, so it should return an empty array.

**Comment by johnml1135** [comment]
I believed that this is a good logic, saying that the build is not completed with pre-translations, when there are none. I will not argue too strongly for it, though as long as the behavior is documented in swagger.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Damien Daspit ***@***.***>
Sent: Friday, August 18, 2023 5:34:23 PM
To: sillsdev/serval ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [sillsdev/serval] Serval incorrectly returns a 404 when there are no pretranslations (Issue #96)


When the pretranslation endpoints are called and there are no pretranslations, then Serval incorrectly returns a 404 error. The pretranslations resource is a collection and should always exist as long as the engine exists. It is simply an empty collection, so it should return an empty array.
