### ISSUE TITLE
Client Helper - Build Engine is a DoS attack

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#98]
Well, not quite - it pings every 500 ms.  This should be made less aggressive.

Here is an idea - I wouldn't want SF and other Clients pinging Serval every 500 ms but we could do this:
* Have cRevision be default not used (with a new parameter called "incrementRequestedRevisionPerCall"
* Make a new parameter ""requestInterval" and default it to 5 seconds.  Override it when calling from a test environment.

**Comment by ddaspit** [comment]
This is why we implemented long polling in the Serval API. Why aren't we using long polling?

**Comment by johnml1135** [comment]
Because with NMT and large SMT models, it will timeout.

**Comment by Enkidu93** [comment]
Should we find a way to fix long-polling then? Thoughts?

**Comment by ddaspit** [comment]
Scripture Forge is using long polling, so we should be using it in our E2E tests. We need to update the E2E tests to use long polling instead of standard polling.

**Comment by johnml1135** [comment]
Except the long polling type doesn't work in NMT right now, or for queueing.  There are no updates within the timeout window.  How should that be addressed (queue depth doesn't change?  Still waiting for clearML to start up (3 minutes))?

**Comment by ddaspit** [comment]
It is perfectly fine if there are no updates within the timeout window. It is designed to work that way. You gracefully handle the 408 and create a new request.

**Comment by johnml1135** [comment]
Ah - design in the 408's - it makes sense because a 408 means "wait - it's coming." rather than "you shouldn't be asking that".  I agree.
