### ISSUE TITLE
S3 bucket health check not showing on /health

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/serval#99]
Fix it.

**Comment by Enkidu93** [comment]
I think that in order for this to work, I'd have to add the logic within Serval itself. Are you OK with removing that wall of abstraction? (Otherwise, I might be able to 'forward' the health check to Serval from Machine). Also, what is the priority here?

**Comment by johnml1135** [comment]
Let's talk next week about how we can approach this.

**Comment by Enkidu93** [comment]
> Let's talk next week about how we can approach this.

We never got to this I don't think. Thoughts, @johnml1135 ?

**Comment by johnml1135** [comment]
You are right - just saying that "Nmt" is degraded is sufficient for Serval clients to determine if the system is healthy or not.
